In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\validated\jobs_validated_20260305_210129.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\cleaned\test_cleaned_data.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\validated\jobs_validated_20260107_095333.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\validated\jobs_validated_20260305_210129.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\general_jobs.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\sample_job.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\test_sample.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\scraped_data.csv")

In [3]:
data.columns

Index(['title', 'company', 'experience', 'salary', 'location', 'education',
       'star_skills', 'normal_skills', 'posted_date', 'last_apply_date',
       'role', 'industry_type', 'department', 'employment_type',
       'role_category', 'description', 'job_url', 'scraped_at', 'job_type'],
      dtype='object')

In [110]:

# Sab columns ko lowercase kar do
data.columns = data.columns.str.lower()

In [111]:
data.head()

,title,company,experience,salary,location,education,star_skills,normal_skills,posted_date,last_apply_date,role,industry_type,department,employment_type,role_category,description,job_url,scraped_at,job_type
0,Data Scientist,Deutsche Bank,4 - 13 years,Not Disclosed,Pune,EducationUG:Any GraduatePG:Any Postgraduate,[],"['Data analysis', 'data science', 'Infrastruct...",2 days ago,09 Sep 2025,"Data Engineer ,","Banking ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,The Deutsche India is seeking a talented Data ...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:40.504260,Data Scientist
1,Data Scientist,Philips,6 - 11 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,[],"['Data analysis', 'SAP', 'Analytical', 'Health...",2 days ago,25 Jul 2024,"Data Scientist ,","Medical Services / Hospital ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,Job Title Data Scientist Job Description Data ...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:43.757232,Data Scientist
2,Data Scientist-Artificial Intelligence,IBM,3 - 7 years,Not Disclosed,Hyderabad,EducationUG:Any GraduatePG:Any Postgraduate,['data scientist'],"['python', 'ai solutions', 'ai frameworks', 'a...",Today,19 Aug 2025,"Data Scientist ,","IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,"As an Associate Data Scientist at IBM, you wil...",https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:47.228273,Data Scientist
3,Data Scientist,Alstom,7 - 12 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,['data scientist'],"['python', 'neural networks', 'ai', 'numpy', '...",2 days ago,09 Nov 2024,"Full Stack Data Scientist ,","Urban Transport ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,Your future role Take on a new challenge and a...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:53.138785,Data Scientist
4,Data Scientist-Artificial Intelligence,IBM,3 - 7 years,Not Disclosed,Bengaluru,"EducationUG:Any GraduatePG:LLM in Law, Any Pos...",['data scientist'],"['kubernetes', 'python', 'ai solutions', 'ai',...",Today,19 Aug 2025,"Full Stack Data Scientist ,","IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,Scale an existing RAG code base for a producti...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:59.775018,Data Scientist

In [112]:
data.columns

Index(['title', 'company', 'experience', 'salary', 'location', 'education',
       'star_skills', 'normal_skills', 'posted_date', 'last_apply_date',
       'role', 'industry_type', 'department', 'employment_type',
       'role_category', 'description', 'job_url', 'scraped_at', 'job_type'],
      dtype='object')

In [113]:
data.isna().sum()

title                 0
company             143
experience            0
salary                0
location              0
education             0
star_skills           0
normal_skills         0
posted_date           0
last_apply_date    8292
role                  0
industry_type         0
department            0
employment_type       0
role_category         0
description           0
job_url               0
scraped_at            0
job_type              0
dtype: int64

In [4]:
from strategies.title_cleaning_strategy import TitleCleaningStrategy

tcs = TitleCleaningStrategy()

In [5]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [6]:
result  = tcs.clean_feature(data["title"])

In [7]:
result.sample(10)

26975       [Database Administrator]
6408                 [Web Developer]
5595              [Business Analyst]
25040    [Machine Learning Engineer]
10176              [DevOps Engineer]
16313            [Software Engineer]
26581            [Software Engineer]
14420      [Ruby on Rails Developer]
21212               [Java Developer]
5726                 [Data Engineer]
Name: title, dtype: object

In [8]:
df["title"] = result
df.sample(10)

                             title
15206     [Database Administrator]
9025               [IT Consultant]
29014                      [Other]
29287             [Data Scientist]
16086               [Data Analyst]
9954             [Product Manager]
23101              [Web Developer]
7442                 [UX Designer]
14488  [Machine Learning Engineer]
28034          [Software Engineer]

In [28]:
temp = df["title"][0]

In [32]:
temp

'Data Scientist'

In [34]:
temp = temp[0]

In [119]:
df["title"].isnull().sum()

0

In [120]:
df["title"].isna().sum()

0

In [121]:
# Company
from strategies.company_cleaning_strategy import CompanyCleaningStrategy
# salary
from strategies.salary_cleaning_strategy import SalaryCleaningStrategy
# education
from strategies.education_cleaning_strategy import EducationCleaningStrategy
# description
from strategies.description_cleaning_strategy import DescriptionCleaningStrategy
# role
from strategies.role_type_cleaning_strategy import RoleCleaningStrategy
# role category
from strategies.role_category_cleaning_strategy import RoleCategoryCleaningStrategy
# location
from strategies.location_cleaning_strategy import LocationCleaningStrategy
# industry type
from strategies.industry_type_cleaning_strategy import IndustryTypeCleaningStrategy
# skill
from strategies.skill_cleaning_strategy import SkillsCleaningStrategy
# timestamp
from strategies.timestamp_cleaning_strategy import TimestampCleaningStrategy
# last apply data
from strategies.last_apply_date_cleaning_strategy import LastApplyDateCleaningStrategy
# department
from strategies.department_cleaning_strategy import DepartmentCleaningStrategy
# experience
from strategies.experience_cleaning_strategy import ExperienceCleaningStrategy
# posted data
from strategies.posted_date_cleaning_strategy import PostedDateCleaningStrategy

In [122]:
data["company"].sample(10)

22178                   Marktine
27499            Prisys Infotech
20555            Godigi Infotech
27361                     Vaaree
11429                  Accenture
9214               Object Source
25754    Wing Global It Services
22509                ACL Digital
13786                      Wipro
6815            Sentient Systems
Name: company, dtype: object

In [123]:
ccs = CompanyCleaningStrategy()
df["company"] = ccs.clean_feature(data["company"])

df.sample(10)

                           title                   company
24762           [Cloud Engineer]      Insight Direct India
3690   [Ruby on Rails Developer]                Railscarma
7212         [Software Engineer]                 Accenture
13106           [Cloud Engineer]         Wissen Technology
14729            [Web Developer]   Intellisense Technology
22949   [Generative AI Engineer]                     Wipro
1692      [Full Stack Developer]               Adani Group
11055         [Technical Writer]              Tsmg Holding
25955     [Mobile App Developer]                  Qcentrio
24089           [Data Scientist]  Jubilant FoodWorks (JFL)

In [124]:
data["salary"].sample(10)

767           Not Disclosed
11784         Not Disclosed
21177         Not Disclosed
20969         Not Disclosed
20392    50,000-1 Lacs P.A.
9979          Not Disclosed
9999          Not Disclosed
6925          Not Disclosed
8524        16-30 Lacs P.A.
13837         Not Disclosed
Name: salary, dtype: object

In [125]:
scs = SalaryCleaningStrategy()
# df["Salary"] = scs.clean_feature(data["Salary"])
result = scs.clean_feature(data["salary"])
result.sample(10)
# df = pd.concat([df,result],axis=1)
df[["min_salary",	"max_salary",	"avg_salary"]]  = result[["min_salary",	"max_salary",	"avg_salary"]]
# df.sample(10)

In [126]:
data["education"].sample(5)

6733                              EducationUG:Any Graduate
26410    EducationUG:B.Tech/B.E. - Bachelor of Technolo...
12654                             EducationUG:Any Graduate
11027                  EducationUG:Any GraduatePG:CA in CA
24739          EducationUG:Any GraduatePG:Any Postgraduate
Name: education, dtype: object

In [ ]:
ecs = EducationCleaningStrategy()

result = ecs.clean_feature(data["education"])

result.sample(10)


df["ug_degree"] = result["ug_degree"]
df["ug_specialization"] = result["ug_specialization"]
df["pg_degree"] = result["pg_degree"]
df["pg_specialization"] = result["pg_specialization"]
# # df = pd.concat([df, result],axis=1)

df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization
192,[Machine Learning Engineer],Red Hat,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None
13476,[Software Engineer],KLA,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None
29221,[Product Manager],Hexaware Technologies,NaN,NaN,NaN,Any Graduate,None,None,None
27865,[Generative AI Engineer],Genpact,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None
27548,[Java Developer],Appextech Software Solutions,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None
1784,[DevOps Engineer],Wipro,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None
20290,[Data Engineer],Accenture,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None
15432,[Data Scientist],Xcellence It,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None
16964,[Scrum Master],SRS Infoway,10.0,15.0,12.5,Any Graduate,None,None,None
20641,[DevOps Specialist],Onzestt Services,NaN,NaN,NaN,B.Tech,None,None,None

In [128]:
data["description"].sample(10)

10818    Project Role : Data Engineer Project Role Desc...
17525    Role & responsibilities Responsible for managi...
15174    About The Role Project Role : Database Adminis...
17443    About The Role Role Purpose The purpose of thi...
6079     Frontend Development (React/Angular): Develop ...
20273    Design and implement scalable data architectur...
27288    General Purpose We are looking for a Front-End...
27003    Key Responsibilities: Design, develop, and mai...
20820    Lead Business Analyst-ERP systems, Finance mod...
616      Your role and responsibilities: We are looking...
Name: description, dtype: object

In [129]:
dcs = DescriptionCleaningStrategy()

df["description"] = dcs.clean_feature(data["description"])

df["description"].sample(10)

6404     Your key responsibilities Basic understanding ...
2959     Role -Full Stack Developer Required Technical ...
25425    Hi Hope everything is fine at your end. We hav...
1336     About The Role Project Role : Custom Software ...
15905    Greetings from HCL Tech we are looking for Ful...
24154    End-to-End ML Pipeline Development Build and o...
13983    Job Summary : The SAP Security Analyst will pl...
26166    Role & responsibilities • Batch record prepara...
26694    Role & responsibilities We are looking for a d...
1810     Urgent opening for Site Reliability Engineer W...
Name: description, dtype: object

In [130]:
data["role"].sample(10)

3864                  Computer Vision ,
23713          Mobile / App Developer ,
19204                  Data Scientist ,
19641        Product Manager - Pharma ,
10251                    Test Analyst ,
19000                  Technical Lead ,
7646         System Security Engineer ,
20910    Software Development - Other ,
11495              Back End Developer ,
10683                Business Analyst ,
Name: role, dtype: object

In [131]:
rcs = RoleCleaningStrategy()

df["role"] = rcs.clean_feature(data["role"])

In [132]:
df["role"].sample(10)

28488    [Database Administrator]
24472        [Back End Developer]
16989        [Back End Developer]
18796                     [Other]
25087                     [Other]
25811          [Network Engineer]
14024      [Full Stack Developer]
8447                      [Other]
24076            [Data Scientist]
17785          [Network Engineer]
Name: role, dtype: object

In [133]:
rccs = RoleCategoryCleaningStrategy()

df["role_category"] = rccs.clean_feature(data["role_category"])

In [134]:
df["role_category"].sample(10)

9822               Software Development
26183                   Technology / It
1806                             DevOps
2032               Software Development
23655                        IT Support
20137                Operations Support
12111                  Customer Success
1426         Product Management - Other
3179                         It Network
905      Pharmaceutical & Biotechnology
Name: role_category, dtype: object

In [135]:
data["industry_type"].sample(10)

4494     IT Services & Consulting ,
15379    IT Services & Consulting ,
17751    IT Services & Consulting ,
12032    IT Services & Consulting ,
9064     IT Services & Consulting ,
7285     IT Services & Consulting ,
8801     IT Services & Consulting ,
22595    IT Services & Consulting ,
10811    IT Services & Consulting ,
1352     IT Services & Consulting ,
Name: industry_type, dtype: object

In [136]:
itc = IndustryTypeCleaningStrategy()

result = itc.clean_feature(data["industry_type"])

result.sample(10)

,industry_types,primary_industry,industry_count
18607,[Telecom / Isp],Telecom / Isp,1
18311,[IT Services & Consulting],IT Services & Consulting,1
21288,[IT Services & Consulting],IT Services & Consulting,1
23385,[IT Services & Consulting],IT Services & Consulting,1
5313,[Engineering & Construction],Engineering & Construction,1
26682,[Banking],Banking,1
13614,[Software Product],Software Product,1
10420,[Automobile (Electric Vehicle (Ev))],Automobile (Electric Vehicle (Ev)),1
12045,[IT Services & Consulting],IT Services & Consulting,1
14683,[IT Services & Consulting],IT Services & Consulting,1

In [137]:
df["industry_type"] = result["primary_industry"]
df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,role,role_category,industry_type
2054,[Mobile App Developer],WP Ninja Infotech,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,WP Ninja Infotech is looking for Mobile App De...,[Other],Software Development,IT Services & Consulting
5949,[Project Manager],Naukri,10.0,24.0,17.00,Not Required,None,None,None,Roles and Responsibilities : Manage IT infrast...,[Other],Technology / It,Internet
20922,[Front End Developer],Supercode,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,We are looking for a talented Frontend Develop...,[Front End Developer],Software Development,Internet
24525,[DevOps Engineer],Ibrowsejobs Technologies,8.0,10.0,9.00,Any Graduate,None,None,None,We are seeking an experienced and professional...,[DevOps Engineer],DevOps,IT Services & Consulting
13376,[Research Associate],Adroit Market Research,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Adroit Market Research is looking for Research...,[Research Associate],Pharmaceutical & Biotechnology,Analytics / Kpo / Research
12915,[Product Manager],Societe Generale Global Solution Centre,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Societe Generale Global Solution Centre is loo...,[Product Manager],Product Management - Technology,IT Services & Consulting
12582,[Business Analyst],Wipro,NaN,NaN,NaN,B.A,None,Any Postgraduate,None,Job Description Role Purpose The purpose of th...,[Business Analyst],Business Intelligence & Analytics,IT Services & Consulting
9178,[Full Stack Developer],Capgemini,NaN,NaN,NaN,Any Graduate,None,None,None,Role & responsibilities Develop and maintain w...,[Other],None,IT Services & Consulting
10575,[Machine Learning Engineer],Qualcomm,NaN,NaN,NaN,B.Tech,Production/Industrial,LLM,Law,"Job Overview: We are seeking ambitious, bright...",[AI Engineer],Quality Assurance And Testing,IT Services & Consulting
9149,[Other],Prudent Solutions,2.5,3.0,2.75,None,None,MBA,HR/Industrial Relations,Candidate will be responsible to handle End to...,[IT Consultant],Other Consulting,IT Services & Consulting

In [138]:
data["department"]

0                 Data Science & Analytics ,
1                 Data Science & Analytics ,
2                 Data Science & Analytics ,
3                 Data Science & Analytics ,
4                 Data Science & Analytics ,
                        ...
29977                                Other ,
29978    Engineering - Hardware & Networks ,
29979    Engineering - Hardware & Networks ,
29980    Engineering - Hardware & Networks ,
29981    Engineering - Hardware & Networks ,
Name: department, Length: 29982, dtype: object

In [139]:
dcs = DepartmentCleaningStrategy()

result = dcs.clean_feature(data["department"])

result.sample(10)

,department_cleaned,primary_department,department_count
12348,"[Engineering, Software Development, Quality As...",Engineering,3
27841,"[Engineering, Software Development, Quality As...",Engineering,3
9628,"[Data Science, Analytics]",Data Science,2
23501,"[Engineering, Software Development, Quality As...",Engineering,3
11167,"[Data Science, Analytics]",Data Science,2
14712,"[Engineering, Software Development, Quality As...",Engineering,3
9707,"[Research & Development, Development]",Research & Development,2
8586,"[Engineering, Software Development, Quality As...",Engineering,3
28888,"[Healthcare, Life Sciences]",Healthcare,2
9121,"[Information Technology, Information Security]",Information Technology,2

In [140]:
df["department"] = result["primary_department"]
df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,role,role_category,industry_type,department
8469,[Research Associate],Aragen Life Sciences,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Aragen is looking for Research Associate to jo...,[Research Associate],Pharmaceutical & Biotechnology,Pharmaceutical & Life Sciences,Research & Development
25750,[Cybersecurity Analyst],Wrike,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,About the Role: Wrike is seeking an experience...,[Cybersecurity Analyst],IT Security,IT Services & Consulting,Information Technology
12810,[Web Developer],Accenture,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,About The Role Project Role : Custom Software ...,[Front End Developer],Software Development,IT Services & Consulting,Engineering
16836,[Mobile App Developer],Hunch Software,NaN,NaN,NaN,B.Tech,Computers,Not Required,None,We are urgently in need of a Mobile App Develo...,[Back End Developer],Software Development,IT Services & Consulting,Engineering
12621,[AI Engineer],Ecolab Global Services,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,"About the Role Youll lead the architecture, de...",[Data Engineer],Software Development,Industrial Equipment / Machinery,Engineering
996,[Web Developer],Asquare Infotech,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,We are looking for an outstanding Web Develope...,[Full Stack Developer],Software Development,IT Services & Consulting,Engineering
15720,[DevOps Engineer],Wipro,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,About The Role Role Purpose The purpose of thi...,[DevOps Engineer],DevOps,IT Services & Consulting,Engineering
6415,[Other],OM Prakash Kumawat,1.8,4.8,3.3,Diploma,None,None,None,"Set up VMC machines, workpiece clamping, tool ...",[Other],Production & Manufacturing - Other,Industrial Equipment / Machinery,Production
24573,[Product Manager],S&P Global Market Intelligence,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,The Role : Join us as Product Manager at SP Gl...,[Product Manager],Product Management - Technology,Banking,Product Management
14695,[Data Engineer],Accenture,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,Project Role : Data Engineer Project Role Desc...,[Data Engineer],Software Development,IT Services & Consulting,Engineering

In [141]:
data["star_skills"].sample(10)

12005    ['IPSEC', 'OSI or TCP/IP model', 'CISSP', 'CCN...
13364                                                   []
450                                    ['Web Development']
26793                                                   []
29308                                   ['data scientist']
24624                                                   []
2655                                     ['data engineer']
1708                                              ['Java']
29295                                   ['data scientist']
10774                                                   []
Name: star_skills, dtype: object

In [142]:
data["normal_skills"].sample(10)

15426    ['Tensorflow', 'NLP', 'Artificial Intelligence...
12331    ['deep learning', 'data science', 'Machine lea...
12512    ['Ml Engineer', 'Gen AI', 'AI ML', 'NLP', 'Art...
12630    ['image processing', 'r', 'predictive modeling...
13964    ['Java', 'ERP', '.Net', 'Ticketing System', 'P...
1484                                    ['GIS', 'Mapping']
5032     ['solution design', 'scrum master', 'design', ...
156      ['data preprocessing', 'natural language proce...
17808    ['css', 'pr', 'ace', 'network engineer', 'cisco']
3814     ['Power Bi', 'Data Cleansing', 'Data Extractio...
Name: normal_skills, dtype: object

In [143]:
data.iloc[2702:2703]

,title,company,experience,salary,location,education,star_skills,normal_skills,posted_date,last_apply_date,role,industry_type,department,employment_type,role_category,description,job_url,scraped_at,job_type
2702,Web Developer,Accenture,3 - 8 years,Not Disclosed,Hyderabad,EducationUG:B.Tech/B.E. in Any SpecializationP...,['web developer'],"['front end', 'css', 'performance monitoring',...",2 days ago,04 Nov 2025,"Full Stack Developer ,","IT Services & Consulting ,","Engineering - Software & QA ,","Full Time, Permanent",Software Development,About The Role Project Role : Web Developer Pr...,https://www.naukri.com/job-listings-web-develo...,2025-12-12T22:52:06.681962,Web Developer

In [144]:
scs = SkillsCleaningStrategy()

result = scs.clean_feature(feature=data[["star_skills","normal_skills"]])

result.sample(10)

                                         combined_skills  skill_count
29231  [Product Management, Automation, Backend, Arch...           10
4591   [Financial Analysis, Security Analysis, Analys...           18
7718   [Switch Configuration, Cisco Firewall, Cisco R...            3
24765  [C#, Mvc, Net, Java, Microsoft Azure, AWS, Pyt...            7
28646  [Python, Operations, Management, Developer, Co...            5
27552         [Java, Elk, Java Spring Boot, Restful Web]            4
5157   [Git, Architecture, Coding, Manager Technology...            7
4918   [Computer Science, System Testing, Testing Too...           10
10663  [Business Analytics, Excel, Power Bi, Data Ana...            5
8085   [Innovation, Excel, Stakeholder Management, Mu...            6

In [145]:
# df = pd.concat([df,result],axis = 1)
df["skills"] = result["combined_skills"]
df["skill_count"] = result["skill_count"]

df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,role,role_category,industry_type,department,skills,skill_count
11225,[Data Analyst],TELUS International,NaN,NaN,NaN,Not Required,None,None,None,Are you a detail-oriented individual with a pa...,[Other],None,IT Services & Consulting,Other,"[Bengali, Fluent English, English, Communicati...",6
327,[Generative AI Engineer],Altimetrik,NaN,NaN,NaN,B.Tech,None,MCA,"Any Specialization, M.Tech in Any Specializati...",GEN AI EngineersRole & responsibilities Are yo...,[Data Engineer],Data Science & Machine Learning,IT Services & Consulting,Data Science,"[Generative Ai, Natural Language Processing, L...",7
10688,[Business Analyst],Wipro,NaN,NaN,NaN,B.A,None,Any Postgraduate,None,Role Purpose The purpose of the role is to lia...,[Business Analyst],Business Intelligence & Analytics,IT Services & Consulting,Data Science,"[Project Management, Software Testing, Busines...",17
16210,[Data Engineer],Amazon,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Data is the new Oil !! Are you passionate abou...,[Data Engineer],Data Science & Machine Learning,Internet,Data Science,"[Object Oriented Design, Data Modeling, Scala,...",10
11273,[Product Manager],Adani Group,NaN,NaN,NaN,Any Graduate,None,None,None,Purpose/Objective Executive Assistant is respo...,[Business Analyst],Business Intelligence & Analytics,Aviation,Data Science,"[Project Management, Competitor Analysis, Data...",16
17728,[Database Administrator],SRS Infoway,18.0,22.5,20.25,Any Graduate,None,None,None,Role & responsibilities Bachelor's degree in C...,[IT Support Specialist],IT Support,IT Services & Consulting,Information Technology,"[Oracle Dba, Sap Basis, Oracle Administration,...",4
23298,[UX Designer],Pineaxe Technologies,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,About iamneo Founded in 2016 and now part of t...,[UX Designer],Other Design,IT Services & Consulting,UX Design,"[User Research, Web Technologies, Interaction ...",8
23542,[Cybersecurity Analyst],Institute of Information Security IIS,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Conduct vulnerability assessment and penetrati...,[Systems Analyst],Quality Assurance And Testing,IT Services & Consulting,Engineering,"[Red, Analyst, It Security, Physical Security,...",8
16173,[Research Associate],Universal Ai University,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Main Roles & Responsibilities Research - 1 Con...,[Research Associate],Pharmaceutical & Biotechnology,Education & Training,Research & Development,"[Usage, Publishing, Literature, Research, Rese...",7
12007,[Network Engineer],Hitachi Consulting ( formerly Information Mana...,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Meet our Team We represent Hitachi Vantara to ...,[Network Engineer],It Network,IT Services & Consulting,Engineering,"[Switching, Eigrp, Bgp, F5, Routing, Velocloud...",25

In [146]:
data["experience"].sample(10)

3621      3 - 8 years
9874      5 - 8 years
17742    8 - 13 years
11023     4 - 9 years
29369    6 - 11 years
23904    6 - 16 years
20360     2 - 7 years
29225     5 - 8 years
17216     3 - 5 years
14709     1 - 4 years
Name: experience, dtype: object

In [147]:
ecs = ExperienceCleaningStrategy()

result = ecs.clean_feature(data["experience"])

In [148]:
result.sample(10)

       min_experience  max_experience
6151             10.0            14.0
17318             3.0             8.0
20402             3.0             5.0
12328             0.0             4.0
25011             2.0             7.0
5473              3.0             5.0
28069             1.0             6.0
21374             4.0             9.0
20288             2.0             4.0
1839              7.0            12.0

In [149]:
data.iloc[388:390]

,title,company,experience,salary,location,education,star_skills,normal_skills,posted_date,last_apply_date,role,industry_type,department,employment_type,role_category,description,job_url,scraped_at,job_type
388,Data Engineer,Mercedes Benz,2 - 4 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,"['python', 'sql queries', 'big data technologi...","['continuous integration', 'ci/cd', 'microsoft...",3 days ago,05 Aug 2024,"Data Engineer ,","Automobile (Automobile Dealers) ,","Engineering - Software & QA ,","Full Time, Permanent",Software Development,Roles & Responsibilities Design & Build Scalab...,https://www.naukri.com/job-listings-data-engin...,2025-12-07T11:45:19.977953,Data Engineer
389,Data Engineer / Data Architect - WFO _ Chenna...,Intellect Design Arena,3 - 8 years,Not Disclosed,"Hyderabad,Chennai",EducationUG:Any Graduate,"['Vector Db', 'Gcp Bigquery', 'Python']","['Vertex', 'Bigquery']",2 weeks ago,02 Nov 2025,"Data Engineer ,","IT Services & Consulting ,","Engineering - Software & QA ,","Full Time, Permanent",Software Development,"Strong hands-on experience with SQL, Python , ...",https://www.naukri.com/job-listings-data-engin...,2025-12-07T11:45:23.405779,Data Engineer

In [150]:
# df = pd.concat([df,result],axis = 1)
df["min_experience"] = result["min_experience"]
df["max_experience"] = result["max_experience"]
df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,role,role_category,industry_type,department,skills,skill_count,min_experience,max_experience
18469,[DevOps Specialist],ZiniosEdge Software Technologies,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,ZiniosEdge Software Technologies Pvt Ltd is lo...,[Other],DevOps,IT Services & Consulting,Engineering,"[Continuous Integration, Kubernetes, Nexus, Gi...",20,5.0,10.0
96,[Data Analyst],Orion,3.0,6.0,4.5,B.Tech,None,None,None,A manufacturing service provider company is cu...,[Other],Other Program / Project Management,Recruitment & Staffing,Project,"[Excellent Communication Skills, Project Manag...",3,2.0,5.0
29545,[Data Engineer],Accenture,NaN,NaN,NaN,Technology Engineering,None,Any Postgraduate,None,About The Role Project Role : Data Engineer Pr...,[Data Engineer],Software Development,IT Services & Consulting,Engineering,"[Data Analytics, Database Design, Data Modelin...",22,2.0,4.0
2873,[Project Manager],Unimech Aerospace,NaN,NaN,NaN,B.Tech,Mechanical,None,None,Key Responsibilities Lead end-to-end execution...,[Project Manager],Other Program / Project Management,Defence & Aerospace,Project,"[Tooling, Project Management, Aerospace Standa...",9,9.0,14.0
14275,[Technical Writer],Vertex Infosoft Solutions,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Requirements: Graduation/Post Graduation (IT/C...,[Web Developer],Content Management (Print / Online / Electronic),IT Services & Consulting,Content,"[Robohelp, Ms Word, Adobe]",3,0.0,3.0
13376,[Research Associate],Adroit Market Research,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Adroit Market Research is looking for Research...,[Research Associate],Pharmaceutical & Biotechnology,Analytics / Kpo / Research,Research & Development,"[Project Management, Data Analysis, Data Inter...",17,0.0,2.0
22178,[Cloud Engineer],Marktine,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,OB SUMMARY:This role serves as subject matter ...,[Other],It Infrastructure Services,IT Services & Consulting,Information Technology,"[Cloud Computing, Automation, Coding, Shell Sc...",10,3.0,8.0
18569,[Cybersecurity Analyst],Visa,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,This position is for an associate Cybersecurit...,[AI Engineer],It Network,IT Services & Consulting,Engineering,"[Automation, Service Level, Hp Data Protector,...",10,3.0,6.0
26570,[Web Developer],Accenture,NaN,NaN,NaN,Technology Engineering,None,Any Postgraduate,None,Project Role : Web Developer Project Role Desc...,[Front End Developer],Software Development,IT Services & Consulting,Engineering,"[Web Developer, Front End, CSS, Version Contro...",14,3.0,8.0
24702,[Full Stack Developer],Yash Technologies,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,YASH Technologies is a leading technology inte...,[QA Engineer],Software Development,IT Services & Consulting,Engineering,"[Continuous Integration, CSS, Go, Ci, Cd, Jdbc...",27,12.0,17.0

In [151]:
data["location"].sample(10)

2808                                             Bengaluru
7063                                                Remote
29443                                            Bengaluru
26533                                            Bengaluru
23383                                  Noida( Sector 142 )
11453    Mumbai Suburban,Navi Mumbai,Mumbai (All Areas)...
10454                                               Nagpur
2381                                Pune,Chennai,Bengaluru
11663                                             Gurugram
17799                                             Gurugram
Name: location, dtype: object

In [152]:
lcs = LocationCleaningStrategy()

result = lcs.clean_feature(data["location"])

In [153]:
result.sample(10)

,location_cities,primary_location,location_count,is_remote
18794,[Udaipur],Udaipur,1,False
18279,"[Mumbai, Navi Mumbai]",Mumbai,2,False
19007,[Hyderabad],Hyderabad,1,False
1139,[Indore],Indore,1,False
6546,[Ahmedabad],Ahmedabad,1,False
1764,"[Warangal, Hyderabad, Nizamabad]",Warangal,3,False
23725,[Bengaluru],Bengaluru,1,False
22047,[Bengaluru],Bengaluru,1,False
13698,[Pune],Pune,1,False
11367,"[Jamnagar, Ahmedabad, Rajkot, Surat, Vadodara]",Jamnagar,5,False

In [154]:
df["location"] = result["primary_location"]
df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,role,role_category,industry_type,department,skills,skill_count,min_experience,max_experience,location
6690,[Project Manager],Relevance Lab,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Lead execution of the assigned projects respon...,[Project Manager],Technology / It,IT Services & Consulting,Project,"[Procurement, Supply Chain, Data Analysis, Cha...",10,7.0,12.0,Bengaluru
15830,[Project Manager],Solarsquare Energy,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,About SolarSquare Energy: At SolarSquare we ar...,[Project Manager],Construction / Manufacturing,Power,Project,"[Supply Chain, Telecom, Field Operations, Team...",10,3.0,5.0,Jaipur
5595,[Business Analyst],Accenture,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,About The Role Project Role : Business Analyst...,[Systems Analyst],Quality Assurance And Testing,IT Services & Consulting,Engineering,"[Business Analyst, Business Models, Websphere,...",21,1.0,4.0,Bengaluru
8976,[Database Administrator],Viable Search Consultants,6.5,10.0,8.25,B.Tech,"Any Specialization, B.Sc in Any Specialization",None,None,"Job Description:- • Develop, test, and deploy ...",[Other],None,IT Services & Consulting,Other,"[Database Administration, Plsql, Oracle, Git, ...",8,3.0,8.0,Mumbai (All Areas)( Bandra West
18240,[DevOps Engineer],Zeen Web Solutions,0.0,1.0,0.50,Any Graduate,None,None,None,DevOps Engineer (Developer-Focused) Apply at: ...,[Other],It & Information Security - Other,IT Services & Consulting,Information Technology,"[Php, Node.js, AWS, Kubernetes, Jenkins, Softw...",13,3.0,6.0,Jaipur( Ajmer Road
6248,[Other],Delhivery,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Delhivery is looking for Associate to join our...,[Other],Audit & Control,Packaging & Containers,Finance,"[Financial Analysis, Risk Management, Statutor...",16,0.0,3.0,Vapi
1315,[Software Engineer],Accenture,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,About The Role Project Role : Custom Software ...,[Back End Developer],Software Development,IT Services & Consulting,Engineering,"[Software Engineer, Application Developer, Aut...",11,3.0,8.0,Bengaluru
18980,[Technical Writer],Amla Commerce,NaN,NaN,NaN,Any Graduate,None,None,None,Position Summary We are looking for a skilled ...,[Web Developer],Content Management (Print / Online / Electronic),IT Services & Consulting,Content,"[Technical Documentation, Api Documentation, R...",11,5.0,7.0,Nagpur
1791,[Site Reliability Engineer],CME Group,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,As a Observability Engineer under Site Reliabi...,[Site Reliability Engineer],DevOps,Banking,Engineering,"[Site Reliability Engineering, Kubernetes, Con...",22,3.0,8.0,Bengaluru
5105,[Java Developer],Infosys,NaN,NaN,NaN,BCA,"Any Specialization, B.Tech/B.E. in Any Special...",None,None,Infosys Hiring Java+Springboot Developers Exci...,[Other],Software Development,IT Services & Consulting,Engineering,"[Java, Hibernate, Spring Mvc, Spring Boot, Mic...",6,4.0,9.0,Hyderabad

In [155]:
data["scraped_at"].sample(10)

6775     2025-12-14T23:53:02.832124
28255    2026-02-23T18:54:15.154394
6782     2025-12-14T23:53:35.144993
28289    2026-02-23T18:57:26.866676
11166    2025-12-19T20:25:32.292577
8514     2025-12-16T21:19:09.368914
27085    2026-02-19T19:14:54.560951
16312    2026-01-16T18:46:07.478451
14668    2026-01-13T18:57:05.318801
4864     2025-12-13T22:38:15.493095
Name: scraped_at, dtype: object

In [156]:
tcs= TimestampCleaningStrategy()

df["timestamp"] = tcs.clean_feature(data["scraped_at"])

In [157]:
df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,role,role_category,industry_type,department,skills,skill_count,min_experience,max_experience,location,timestamp
9743,[Data Engineer],Altimetrik,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,"Hi, Altimetrik is hiring for Data engineer. Da...",[Data Engineer],Software Development,IT Services & Consulting,Engineering,"[Python, Data Engineer, Pyspark, AWS, SQL]",5,5.0,10.0,Hyderabad,2025-12-17
24585,[Product Manager],Cvent,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Develop an in-depth understanding of the busin...,[Product Manager],Product Management - Technology,IT Services & Consulting,Product Management,"[Product Management, Hospitality, Analytical, ...",10,4.0,9.0,Gurugram,2026-02-13
10360,[AI Engineer],CGI,NaN,NaN,NaN,Any Graduate,None,CA,CA,"Company Profile: Founded in 1976, CGI is among...",[Site Reliability Engineer],DevOps,IT Services & Consulting,Engineering,"[Computer Science, Business Process, Linux, Ld...",10,3.0,4.0,Bengaluru,2025-12-17
19086,[Java Developer],Capgemini,NaN,NaN,NaN,Any Graduate,None,None,None,Job Title: Java Developer Location: Pune Exper...,[Other],It & Information Security - Other,IT Services & Consulting,Information Technology,"[Java, AWS, J2Se, Spring Boot, J2Ee, Jee, Spri...",8,4.0,6.0,Pune,2026-01-24
28985,[Research Associate],Thepharmadaily,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,"Chemical Synthesis Purification : Synthesize, ...",[Database Administrator],IT Security,Medical Services / Hospital,Information Technology,"[Organic Chemistry, Cro, Medicinal Chemistry, ...",10,0.0,2.0,Noida,2026-02-26
14192,[QA Engineer],Crisil,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Role Summary We are seeking a QA Engineer - Pa...,[AI Engineer],Quality Assurance And Testing,Financial Services,Engineering,"[Automation, Payment Processing, Iso, Operatio...",10,6.0,10.0,Mumbai,2025-12-28
503,[Software Engineer],Accenture,NaN,NaN,NaN,B.Tech,None,Any Postgraduate,None,About The Role Project Role : Custom Software ...,[Full Stack Developer],Software Development,IT Services & Consulting,Engineering,"[Software Engineer, Application Developer, CSS...",15,3.0,8.0,Jaipur,2025-12-07
22021,[Project Manager],Niit Learning Systems,16.0,20.0,18.0,Any Graduate,None,None,None,This is 1 year contract role with the scope of...,[Other],Operations,Education & Training,Customer Success,"[Project Management, Project Delivery, Operati...",18,10.0,15.0,Gurugram,2026-02-01
4527,[Cloud Engineer],Altimetrik,NaN,NaN,NaN,Any Graduate,None,None,None,Name(as per aadhar card): Number: EmailID: Cur...,[Other],None,Software Product,Other,"[Cloud Engineering, Terraform, Cloud, Infrastr...",7,5.0,9.0,Pune,2025-12-13
20866,[IT Support Specialist],Taskus,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Key Responsibilities: You will respond to tele...,[IT Support Specialist],IT Support,Management Consulting,Information Technology,"[Bpo, Computer Science, Computer Hardware, Pro...",10,2.0,3.0,Indore,2026-01-27

In [158]:
data["last_apply_date"].sample(10)

8061     20 Jun 2025
12909    06 Oct 2025
24263    11 Jan 2026
8463             NaN
14138    19 Dec 2024
16985    20 Jun 2025
29102    04 Nov 2025
19654    31 Jul 2025
6811     06 Apr 2025
15117    23 Oct 2025
Name: last_apply_date, dtype: object

In [159]:
lcs = LastApplyDateCleaningStrategy()
result = lcs.clean_feature(data["last_apply_date"])
df["last_apply_date"] = result

In [160]:
result.sample(10)

22633    2025-10-20
19150          None
19287    2025-10-14
12831    2025-12-06
18840          None
23817    2025-03-26
8350     2025-04-10
8006           None
7846           None
11216    2024-06-12
Name: last_apply_date, dtype: object

In [161]:
df.sample(10)

,title,company,min_salary,max_salary,avg_salary,ug_degree,ug_specialization\t,pg_degree,pg_specialization,description,...,role_category,industry_type,department,skills,skill_count,min_experience,max_experience,location,timestamp,last_apply_date
10369,[Web Developer],Flex,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Flex is the diversified manufacturing partner ...,...,Software Development,Consumer Electronics & Appliances,Engineering,"[Nunit, Linq, Front End, Flex, Unit Testing, I...",9,4.0,10.0,Chennai,2025-12-17,2024-08-29
23525,[Cybersecurity Analyst],Bruker,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Bruker is enabling scientists to make breakthr...,...,IT Security,Pharmaceutical & Life Sciences,Information Technology,"[Unix, Computer Science, Linux, Microbiology, ...",10,2.0,3.0,New Delhi,2026-02-09,None
23418,[Cloud Engineer],I Care,3.0,5.0,4.0,Any Graduate,None,None,None,M365 expert with 3+ yrs experience in Microsof...,...,It Infrastructure Services,IT Services & Consulting,Information Technology,"[Cloud Operations, Cloud Support, Cloud Migrat...",5,2.0,5.0,Chennai,2026-02-09,None
14388,[Ruby on Rails Developer],Virtueinfo,NaN,NaN,NaN,BCA,"Computers, B.Tech/B.E. in Production/Industrial",MCA,Computers,Job DescriptionWe are looking for a Ruby on Ra...,...,Software Development,IT Services & Consulting,Engineering,"[Hospitality, Jquery, Front End, NoSQL, JavaSc...",10,2.0,4.0,Ahmedabad,2025-12-29,None
15433,[Machine Learning Engineer],New Groyp Talentoj,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,you will have the opportunity to significantly...,...,Data Science & Machine Learning,Software Product,Data Science,"[Classical Machine Learning, Deep Learning, Py...",15,6.0,11.0,Bengaluru,2026-01-15,None
25173,[AI Engineer],Adobe,NaN,NaN,NaN,Any Graduate,None,LLM,Law,Our Company Changing the world through digital...,...,Software Development,IT Services & Consulting,Engineering,"[Innovation, Kubernetes, Python, Modeling, Nat...",16,2.0,5.0,Bengaluru,2026-02-16,2026-02-02
1529,[UX Designer],Hexaware Technologies,NaN,NaN,NaN,Any Graduate,None,None,None,Location : All Hexaware location Notice Period...,...,Software Development,IT Services & Consulting,Engineering,"[Ux Design, Visual Design, Wireframe]",3,9.0,12.0,Hyderabad,2025-12-11,2025-09-05
1987,[Other],Seymour Systems,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Seymour Systems is looking for System Architec...,...,Software Development,IT Services & Consulting,Engineering,"[System Architects, Analysts]",2,2.0,7.0,Hyderabad,2025-12-12,None
4847,[Web Developer],IBM,NaN,NaN,NaN,Any Graduate,None,Any Postgraduate,None,Your role and responsibilities As our Front En...,...,Software Development,IT Services & Consulting,Engineering,"[CSS, JavaScript, React, HTML, TypeScript, Fro...",23,2.0,6.0,Bengaluru,2025-12-13,2025-10-15
22096,[UX Designer],Zebra Technologies,NaN,NaN,NaN,Any Graduate,None,None,None,Overview A UX designer II will help contribute...,...,Other Design,IT Services & Consulting,UX Design,"[Development, Ux, Prototyping, Presentation Sk...",20,3.0,6.0,Bengaluru,2026-02-01,None

In [162]:
df["no_of_applicant"] = None
df["no_of_opening"] = None

In [163]:
df["no_of_applicant"]

0        None
1        None
2        None
3        None
4        None
         ...
29977    None
29978    None
29979    None
29980    None
29981    None
Name: no_of_applicant, Length: 29982, dtype: object

In [164]:
data["posted_date"].sample(10)

3022       1 week ago
8654       1 week ago
14066       1 day ago
9965       1 week ago
20032      1 week ago
13385      4 days ago
27100     2 weeks ago
10981      3 days ago
26631      3 days ago
2068     3+ weeks ago
Name: posted_date, dtype: object

In [165]:
pcs = PostedDateCleaningStrategy()

result = pcs.clean_feature(data[["posted_date","scraped_at"]])

In [166]:
result.sample(10)

      posted_date_parsed  days_since_posted
3095          2025-11-28               14.0
14999         2026-01-07                6.0
21958         2026-01-30                2.0
27785         2026-01-26               28.0
6443          2025-11-16               28.0
26921         2026-01-22               28.0
9002          2025-11-18               28.0
6767          2025-12-07                7.0
19575         2026-01-23                2.0
9465          2025-12-12                5.0

In [167]:
df["posted_timestamp"] = result["posted_date_parsed"]

In [168]:
df.columns

Index(['title', 'company', 'min_salary', 'max_salary', 'avg_salary',
       'ug_degree', 'ug_specialization\t', 'pg_degree', 'pg_specialization',
       'description', 'role', 'role_category', 'industry_type', 'department',
       'skills', 'skill_count', 'min_experience', 'max_experience', 'location',
       'timestamp', 'last_apply_date', 'no_of_applicant', 'no_of_opening',
       'posted_timestamp'],
      dtype='object')

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29982 entries, 0 to 29981
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               29982 non-null  object
 1   company             29982 non-null  object
 2   min_salary          4075 non-null   float64
 3   max_salary          4075 non-null   float64
 4   avg_salary          4075 non-null   float64
 5   ug_degree           29451 non-null  object
 6   ug_specialization	  2622 non-null   object
 7   pg_degree           21847 non-null  object
 8   pg_specialization   2201 non-null   object
 9   description         29982 non-null  object
 10  role                29982 non-null  object
 11  role_category       29365 non-null  object
 12  industry_type       29973 non-null  object
 13  department          29982 non-null  object
 14  skills              29982 non-null  object
 15  skill_count         29982 non-null  int64
 16  min_experience      29873 non-null  float64
 17  max_experience      29873 non-null  float64
 18  location            29982 non-null  object
 19  timestamp           29982 non-null  object
 20  last_apply_date     21402 non-null  object
 21  no_of_applicant     0 non-null      object
 22  no_of_opening       0 non-null      object
 23  posted_timestamp    28432 non-null  object
dtypes: float64(5), int64(1), object(18)
memory usage: 5.5+ MB

In [69]:
df.to_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\cleaned\cleaned_data.csv")

In [70]:
df.isna().sum()

title                   0
company                 0
min_salary          25907
max_salary          25907
avg_salary          25907
description             0
role                    0
role_category         617
industry_type           9
department              0
skills                  0
skill_count             0
min_experience        109
max_experience        109
location                0
timestamp               0
last_apply_date      8580
no_of_applicant     29982
no_of_opening       29982
posted_timestamp     1550
dtype: int64

In [71]:
df = df.rename(columns=str.lower)

In [72]:
import os
import sys

In [73]:
os.getcwd()

'd:\\DATA SCIENCE AND ML\\Project\\job_trend_predictor\\src\\cleaners'

In [170]:
import sys
import os

# Go up two levels from notebooks/ → project root
project_root = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Optional: print to confirm
print("Project root added to sys.path:", project_root)
print("Current sys.path[0]:", sys.path[0])

Project root added to sys.path: d:\DATA SCIENCE AND ML\Project\job_trend_predictor
Current sys.path[0]: d:\DATA SCIENCE AND ML\Project\job_trend_predictor

In [171]:
from src.cleaners.job_data_cleaner import JobDataCleaner

In [172]:
config_path = r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\config\cleaning_config.yaml"

jdc = JobDataCleaner(config_path)

In [173]:
result = jdc.clean(data, "title")

In [174]:
result.columns

Index(['title', 'company', 'experience', 'salary', 'location', 'education',
       'star_skills', 'normal_skills', 'posted_date', 'last_apply_date',
       'role', 'industry_type', 'department', 'employment_type',
       'role_category', 'description', 'job_url', 'scraped_at', 'job_type',
       'title_cleaned'],
      dtype='object')

In [79]:
result = jdc.clean_all(data)

In [80]:
result.columns

Index(['title', 'company', 'experience', 'salary', 'location', 'education',
       'star_skills', 'normal_skills', 'posted_date', 'last_apply_date',
       'role', 'industry_type', 'department', 'employment_type',
       'role_category', 'description', 'job_url', 'scraped_at', 'job_type',
       'title_cleaned', 'company_cleaned', 'location_cities',
       'primary_location', 'location_count', 'is_remote', 'min_salary',
       'max_salary', 'avg_salary', 'min_experience', 'max_experience',
       'ug_degree', 'ug_specialization', 'pg_degree', 'pg_specialization',
       'combined_skills', 'skill_count', 'department_cleaned',
       'primary_department', 'department_count', 'scraped_at_cleaned',
       'description_cleaned', 'last_apply_date_cleaned', 'posted_date_parsed',
       'days_since_posted', 'employment_types', 'primary_employment',
       'employment_count', 'industry_types', 'primary_industry',
       'industry_count', 'role_category_cleaned', 'role_cleaned'],
      dtype='object')

In [81]:
df.to_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\cleaned\cleaned_data.csv")

In [175]:
result["Title_cleaned"].sample(10)

KeyError: 'Title_cleaned'

In [ ]:
result["Company_cleaned"].sample(10)

5925                    Surveysparrow
10143                          Amdocs
27781                           FedEx
22015                         Virtusa
5333                        Accenture
2589                 Chaperon Biotech
3936          Millennium Organisation
19962     SWS Smart Working Solutions
24305    Manpowergroup Services India
3898              ZeMoSo Technologies
Name: Company_cleaned, dtype: object

In [ ]:
result["Education_PG_Degree_cleaned"].sample(10)

17970    Not Required
14367            None
20261    Not Required
2846     Not Required
15608    Not Required
20571    Not Required
20902            None
21537    Not Required
27839    Not Required
1068     Not Required
Name: Education_PG_Degree_cleaned, dtype: object

### Fresher Data

In [176]:
import pandas as pd
from sqlalchemy import create_engine

def get_engine(user, password, host, db):
    # The connection string (URL) follows this format:
    # dialect+driver://username:password@host:port/database
    # connection_url = f"mysql+mysqlconnector://{user}:{password}@{host}/{db}"
    # Change mysql+mysqlconnector to mysql+pymysql
    connection_url = f"mysql+pymysql://{user}:{password}@{host}/{db}"
    
    # create_engine returns an Engine object that pandas understands
    engine = create_engine(connection_url)
    return engine

# usage
engine = get_engine("root", "harshit", "localhost", "job_trends")
data = pd.read_sql_table("raw_job_data", engine)
# Load only 1000 rows at a time
# chunks = pd.read_sql_table("raw_job_data", engine, chunksize=1000)

# Iterate through chunks and clean them one by one
# for chunk in chunks:
#     # result = jdc.clean_all(chunk) 
#     print(f"Processed chunk with {len(chunk)} rows")

In [177]:
data.head()

,id,job_id,title,company,experience,salary,location,education,star_skills,normal_skills,...,num_applicants,role,industry_type,department,employment_type,role_category,job_type,description,job_url,scraped_at
0,1,4511587,Python Developer - Fresher,TCS,0-1 Yrs,3-5 Lacs P.A.,Bengaluru,B.Tech/B.E.,"[""Python"", ""Django"", ""SQL""]","[""Git"", ""REST API""]",...,120,Software Development,IT Services,Engineering,Full Time,Programming,python-developer,Looking for fresh graduates...,https://example.com/job1,2026-01-26 10:30:00
1,2,070226018943,Data Analyst,Posted by Tele Infotech,0 - 2 years,2.75-5 Lacs P.A.,"Pimpri-Chinchwad,Pune","EducationUG:Diploma in Any Specialization, Any...","[""Data Analytics""]","[""Large Databases"", ""Google Sheets"", ""Google D...",...,100,Data Science & Analytics - Other,"IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,We are looking for a motivated and detail-orie...,https://www.naukri.com/job-listings-data-analy...,2026-02-08 09:19:53
2,3,020825500433,Trainee AI ML,Vertexplus Technologies,No fixed duration,Unpaid,Jaipur,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""python"", ""data analysis"", ""data analytics"", ...",...,100,Data Science & Machine Learning,"IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,Passion for artificial intelligence and machin...,https://www.naukri.com/job-listings-trainee-ai...,2026-03-11 19:45:59
3,4,040226008743,Data Analytic | Fresher | Business Analytics,Posted by Creative Hands HR,0 - 5 years,2.5-6 Lacs P.A.,"Hyderabad,Chennai,Bengaluru",EducationUG:Any GraduatePG:Any Postgraduate,"[""excel"", ""Business Research"", ""Data Analytics...","[""Data Analyst"", ""Market Research""]",...,100,Data Science & Analytics - Other,"BPM / BPO ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,ANY DEGREE IS PREFERRED 1>good Logical Skills....,https://www.naukri.com/job-listings-data-analy...,2026-02-08 09:20:01
4,5,060226501811,Data Analyst,ADA Global,0 - 1 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""python"", ""data analysis"", ""data analytics"", ...",...,100,Business Intelligence & Analytics,"Management Consulting ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,We are seeking a Data Analyst (Fresher) to joi...,https://www.naukri.com/job-listings-data-analy...,2026-03-11 19:04:46

In [178]:
data.columns

Index(['id', 'job_id', 'title', 'company', 'experience', 'salary', 'location',
       'education', 'star_skills', 'normal_skills', 'posted_date',
       'last_apply_date', 'num_openings', 'num_applicants', 'role',
       'industry_type', 'department', 'employment_type', 'role_category',
       'job_type', 'description', 'job_url', 'scraped_at'],
      dtype='object')

In [179]:
data.shape

(2551, 23)

In [180]:
result = jdc.clean_all(data)

In [181]:
result.sample(10)

,id,job_id,title,company,experience,salary,location,education,star_skills,normal_skills,...,posted_date_parsed,days_since_posted,employment_types,primary_employment,employment_count,industry_types,primary_industry,industry_count,role_category_cleaned,role_cleaned
126,127,230126006940,Remote Backend Developer (Fresher & Junior),Supercoder,0 - 4 years,Not Disclosed,Korea,EducationUG:Bachelor of Commerce (B.Com) in An...,"[""Backend""]","[""Golang"", ""Java"", ""C++"", ""Rust"", ""NoSQL"", ""Dj...",...,None,None,"[Full Time, Permanent]",Full Time,2,[IT Services & Consulting],IT Services & Consulting,1,None,[Other]
2274,17231,270226916336,Network Engineer,Teleperformance (TP),1 - 2 years,Not Disclosed,Thane,EducationUG:B.Tech/B.E. - Bachelor of Technolo...,"[""network engineer""]","[""customer experience management"", ""it systems...",...,None,None,"[Full Time, Permanent]",Full Time,2,[Bpm / Bpo],Bpm / Bpo,1,None,[Network Engineer]
1122,4140,080925005029,Staff Nurse,D Y Patil University (DYPU),1 - 5 years,Not Disclosed,Talegaon-Dabhade,EducationUG:Bachelor of Science (B.Sc) in Nurs...,"[""Nursing Care"", ""Communication Skills"", ""Pati...","[""Emergency Response"", ""Infection Control"", ""M...",...,None,None,"[Full Time, Permanent]",Full Time,2,[Medical Services / Hospital],Medical Services / Hospital,1,None,[Other]
2047,14591,060126029601,Assistant Product Manager,IndiaMART,0 - 3 years,Not Disclosed,Noida,EducationPG:MBA/PGDM,"[""Product Management""]","[""Gtm Strategy"", ""Agile Methodology"", ""Product...",...,None,None,"[Full Time, Permanent]",Full Time,2,[Internet (E-Commerce)],Internet (E-Commerce),1,None,[Product Manager]
2467,18528,050326502976,Associate Business Analyst,TSS Consultancy,0 - 2 years,Not Disclosed,Rajkot,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""Training"", ""Data analysis"", ""Project trackin...",...,None,None,"[Full Time, Permanent]",Full Time,2,[IT Services & Consulting],IT Services & Consulting,1,None,[Business Intelligence Analyst]
2293,17435,280226016828,Junior Software Developer,Anglofone Education,0 - 1 years,Not Disclosed,Coimbatore( Gandhipuram ),EducationUG:Any Graduate,"[""Python""]","[""Ai Techniques"", ""React Native"", ""AWS""]",...,None,None,"[Full Time, Permanent]",Full Time,2,[Education & Training],Education & Training,1,None,[Other]
505,1178,010725500341,Associate Data Engineer - R&D Omics,Amgen Inc,1 - 6 years,Not Disclosed,Hyderabad,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""Computer science"", ""Data analysis"", ""Data mo...",...,None,None,"[Full Time, Permanent]",Full Time,2,[Pharmaceutical & Life Sciences],Pharmaceutical & Life Sciences,1,None,[Other]
2119,14863,250226020234,Junior Data Analyst,WTP Cost Management,1 - 3 years,Not Disclosed,Mumbai (All Areas)( Vikhroli West ),EducationUG:B.Tech/B.E. - Bachelor of Technolo...,"[""Data Analysis"", ""Data Analytics""]","[""Power Bi"", ""Pandas"", ""SQL Queries"", ""Data Ex...",...,None,None,"[Full Time, Permanent]",Full Time,2,[Industrial Equipment / Machinery (Constructio...,Industrial Equipment / Machinery (Construction...,1,None,[Business Intelligence Analyst]
2503,18797,110326928982,Fresher Full Stack Developer,Parsh Technologies Llp,0 - 1 years,Not Disclosed,Rajkot,EducationUG:B.Sc - Bachelor of Science in Comp...,"[""Next js""]","[""RabbitMQ"", ""Framer Motion"", ""Kafka"", ""Node j...",...,None,None,"[Full Time, Permanent]",Full Time,2,[IT Services & Consulting],IT Services & Consulting,1,None,[Other]
1902,12694,200226503112,UCoE Upgrade Engineer (BP Upgrades),Zensar,0 - 2 years,Not Disclosed,Pune,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""BPO"", ""Database architecture"", ""Automation"",...",...,None,None,"[Full Time, Permanent]",Full Time,2,[IT Services & Consulting],IT Services & Consulting,1,None,[Other]

In [184]:
result.columns

Index(['id', 'job_id', 'title', 'company', 'experience', 'salary', 'location',
       'education', 'star_skills', 'normal_skills', 'posted_date',
       'last_apply_date', 'num_openings', 'num_applicants', 'role',
       'industry_type', 'department', 'employment_type', 'role_category',
       'job_type', 'description', 'job_url', 'scraped_at', 'title_cleaned',
       'company_cleaned', 'location_cities', 'primary_location',
       'location_count', 'is_remote', 'min_salary', 'max_salary', 'avg_salary',
       'min_experience', 'max_experience', 'ug_degree', 'ug_specialization',
       'pg_degree', 'pg_specialization', 'combined_skills', 'skill_count',
       'department_cleaned', 'primary_department', 'department_count',
       'scraped_at_cleaned', 'description_cleaned', 'last_apply_date_cleaned',
       'posted_date_parsed', 'days_since_posted', 'employment_types',
       'primary_employment', 'employment_count', 'industry_types',
       'primary_industry', 'industry_count', 'role_category_cleaned',
       'role_cleaned'],
      dtype='object')

In [189]:
result["no_of_opening"] = data["num_openings"]
result["no_of_applicant"] = data["num_applicants"]

In [186]:
columns = ['title_cleaned','company_cleaned', 'primary_location', 'min_salary', 'max_salary', 'avg_salary',
'min_experience', 'max_experience', 'ug_degree', 'ug_specialization',
       'pg_degree', 'pg_specialization', 'combined_skills', 'skill_count','primary_department',
       'scraped_at_cleaned', 'description_cleaned', 'last_apply_date_cleaned',
       'posted_date_parsed',
       'primary_employment',
       'primary_industry', 'role_category_cleaned',
       'role_cleaned']

result = result[columns]

In [187]:
# Best for fixing that 'ug_specialization\t' typo
result = result.rename(columns={
   'title_cleaned':'title' ,
   'company_cleaned': 'company' ,
    'primary_location': 'location',
    'primary_department':'department' ,
    'scraped_at_cleaned': 'scraped_at', 
    'description_cleaned':'description' ,
    'last_apply_date_cleaned': 'last_apply_date',
    'posted_date_parsed':'posted_date' ,
    'primary_employment': 'employment',
    'primary_industry':'industry_type', 
    'role_category_cleaned':'role_category',
    'role_cleaned':'role'
})

In [190]:
result.columns

Index(['title', 'company', 'location', 'min_salary', 'max_salary',
       'avg_salary', 'min_experience', 'max_experience', 'ug_degree',
       'ug_specialization', 'pg_degree', 'pg_specialization',
       'combined_skills', 'skill_count', 'department', 'scraped_at',
       'description', 'last_apply_date', 'posted_date', 'employment',
       'industry_type', 'role_category', 'role', 'no_of_opening',
       'no_of_applicant'],
      dtype='object')

In [239]:
result.sample(10)

,title,company,location,min_salary,max_salary,avg_salary,min_experience,max_experience,ug_degree,ug_specialization,...,scraped_at,description,last_apply_date,posted_date,employment,industry_type,role_category,role,no_of_opening,no_of_applicant
2441,[Web Developer],Transight Systems,Kochi,2.25,4.0,3.12,1.0,2.0,Applications,"Computer Applications (General), B.Tech/B.E. -...",...,None,We are seeking a Junior Django Developer with ...,2025-02-19,None,Full Time,Telecom / Isp,None,[Other],4.0,100
964,[Other],Inovance Technology,Chennai,NaN,NaN,NaN,1.0,6.0,Any Graduate,None,...,None,INOVANCE TECHNOLOGY PRIVATE LIMITED is looking...,None,None,Full Time,IT Services & Consulting,None,[Business Intelligence Analyst],1.0,100
1930,[Web Developer],Infokeys,Delhi / Ncr,NaN,NaN,NaN,1.0,2.0,Any Graduate,None,...,None,What we're looking for We are seeking an exper...,None,None,Full Time,Software Product,None,[Other],1.0,100
650,[Other],U & V Cancure,New Delhi,2.50,3.5,3.00,1.0,3.0,Bachelor of Pharmacy (B.Pharma) in Pharmaceutical,None,...,None,We Are looking a Product Executive to manage p...,None,None,Full Time,Pharmaceutical & Life Sciences,None,[Product Manager],1.0,20
127,[Other],Lumenore,Bhopal,NaN,NaN,NaN,0.0,1.0,Any Graduate,None,...,None,"Develop high-quality, responsive, and interact...",None,None,Full Time,IT Services & Consulting,None,[Other],1.0,100
1604,[Other],JobShop,Bengaluru,3.00,4.5,3.75,0.0,5.0,Not Required,None,...,None,"Greetings from JobShop, Indias Largest BPO Rec...",None,None,Full Time,Bpm / Bpo,None,[Other],120.0,10
141,[Other],Codevibe Technology,Surat,NaN,NaN,NaN,3.0,3.0,Any Graduate,None,...,None,CodeVibe Technology is looking for Trainee to ...,None,None,Full Time,IT Services & Consulting,None,[Other],1.0,50
1901,[Full Stack Developer],Xnexus Platforms,Hyderabad,NaN,NaN,NaN,0.0,1.0,Technology Engineering,"Any Specialization, BCA - Bachelor of Computer...",...,None,"Hiring fresher (0–1 yr) with enthusiasm, creat...",None,None,Full Time,IT Services & Consulting,None,[Other],4.0,100
86,[AI Engineer],Allied Engineering Works,New Delhi( Jahangir Puri,1.25,2.5,1.88,0.0,1.0,B.Tech,None,...,None,We’re Hiring: BTech Electrical Fresher – Gradu...,2026-01-29,None,Full Time,Electronics Manufacturing (Electronic Manufact...,None,[Other],6.0,12
926,[AI Engineer],Amtech Electronics,Gandhinagar,NaN,NaN,NaN,1.0,5.0,Any Graduate,None,...,None,Amtech Electronics is looking for Engineer Qua...,2024-06-19,None,Full Time,Industrial Equipment / Machinery,None,[Other],1.0,100

In [240]:
result.to_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\cleaned\fresher_data")