In [31]:
import pandas as pd

In [37]:
data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\validated\jobs_validated_20260305_210129.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\cleaned\test_cleaned_data.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\validated\jobs_validated_20260107_095333.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\processed\validated\jobs_validated_20260305_210129.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\general_jobs.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\sample_job.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\test_sample.csv")
# data = pd.read_csv(r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\data\raw\scraped_data.csv")

In [38]:
data.columns

Index(['title', 'company', 'experience', 'salary', 'location', 'education',
       'star_skills', 'normal_skills', 'posted_date', 'last_apply_date',
       'role', 'industry_type', 'department', 'employment_type',
       'role_category', 'description', 'job_url', 'scraped_at', 'job_type'],
      dtype='object')

In [23]:

# Sab columns ko lowercase kar do
data.columns = data.columns.str.lower()

In [3]:
data.head()

,Title,Company,Experience,Salary,Location,Education,Star_Skills,Normal_Skills,Posted_Date,Last_Apply_Date,Role,Industry Type,Department,Employment Type,Role Category,Description,Job_URL,Scraped_At,Job_Type
0,Data Scientist,Deutsche Bank,4 - 13 years,Not Disclosed,Pune,EducationUG:Any GraduatePG:Any Postgraduate,[],"['Data analysis', 'data science', 'Infrastruct...",2 days ago,09 Sep 2025,"Data Engineer ,","Banking ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,The Deutsche India is seeking a talented Data ...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:40.504260,Data Scientist
1,Data Scientist,Philips,6 - 11 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,[],"['Data analysis', 'SAP', 'Analytical', 'Health...",2 days ago,25 Jul 2024,"Data Scientist ,","Medical Services / Hospital ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,Job Title Data Scientist Job Description Data ...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:43.757232,Data Scientist
2,Data Scientist-Artificial Intelligence,IBM,3 - 7 years,Not Disclosed,Hyderabad,EducationUG:Any GraduatePG:Any Postgraduate,['data scientist'],"['python', 'ai solutions', 'ai frameworks', 'a...",Today,19 Aug 2025,"Data Scientist ,","IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,"As an Associate Data Scientist at IBM, you wil...",https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:47.228273,Data Scientist
3,Data Scientist,Alstom,7 - 12 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,['data scientist'],"['python', 'neural networks', 'ai', 'numpy', '...",2 days ago,09 Nov 2024,"Full Stack Data Scientist ,","Urban Transport ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,Your future role Take on a new challenge and a...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:53.138785,Data Scientist
4,Data Scientist-Artificial Intelligence,IBM,3 - 7 years,Not Disclosed,Bengaluru,"EducationUG:Any GraduatePG:LLM in Law, Any Pos...",['data scientist'],"['kubernetes', 'python', 'ai solutions', 'ai',...",Today,19 Aug 2025,"Full Stack Data Scientist ,","IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",Data Science & Machine Learning,Scale an existing RAG code base for a producti...,https://www.naukri.com/job-listings-data-scien...,2025-12-03T21:54:59.775018,Data Scientist

In [4]:
data.columns

Index(['Title', 'Company', 'Experience', 'Salary', 'Location', 'Education',
       'Star_Skills', 'Normal_Skills', 'Posted_Date', 'Last_Apply_Date',
       'Role', 'Industry Type', 'Department', 'Employment Type',
       'Role Category', 'Description', 'Job_URL', 'Scraped_At', 'Job_Type'],
      dtype='object')

In [75]:
data.isna().sum()

Title                 0
Company             143
Experience            0
Salary                0
Location              0
Education             0
Star_Skills           0
Normal_Skills         0
Posted_Date           0
Last_Apply_Date    8292
Role                  0
Industry Type         0
Department            0
Employment Type       0
Role Category         0
Description           0
Job_URL               0
Scraped_At            0
Job_Type              0
dtype: int64

In [5]:
from strategies.title_cleaning_strategy import TitleCleaningStrategy

tcs = TitleCleaningStrategy()

In [6]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [7]:
result  = tcs.clean_feature(data["Title"])

In [8]:
result.sample(10)

17148    [Machine Learning Engineer]
14356             [Python Developer]
5751                 [Data Engineer]
3289                 [Web Developer]
10799                [Data Engineer]
24812       [Database Administrator]
27325           [Back End Developer]
22623                 [Scrum Master]
8086              [Python Developer]
10962              [DevOps Engineer]
Name: Title, dtype: object

In [79]:
df["title"] = result
df.sample(10)

                             title
28849               [Data Analyst]
24624            [Project Manager]
16076               [Data Analyst]
2871             [Project Manager]
9164       [IT Support Specialist]
3789   [Machine Learning Engineer]
28613           [Python Developer]
25372          [Software Engineer]
6156             [DevOps Engineer]
1322           [Software Engineer]

In [10]:
df["title"].isnull().sum()

0

In [11]:
df["title"].isna().sum()

0

In [80]:
# Company
from strategies.company_cleaning_strategy import CompanyCleaningStrategy
# salary
from strategies.salary_cleaning_strategy import SalaryCleaningStrategy
# education
from strategies.education_cleaning_strategy import EducationCleaningStrategy
# description
from strategies.description_cleaning_strategy import DescriptionCleaningStrategy
# role
from strategies.role_type_cleaning_strategy import RoleCleaningStrategy
# role category
from strategies.role_category_cleaning_strategy import RoleCategoryCleaningStrategy
# location
from strategies.location_cleaning_strategy import LocationCleaningStrategy
# industry type
from strategies.industry_type_cleaning_strategy import IndustryTypeCleaningStrategy
# skill
from strategies.skill_cleaning_strategy import SkillsCleaningStrategy
# timestamp
from strategies.timestamp_cleaning_strategy import TimestampCleaningStrategy
# last apply data
from strategies.last_apply_date_cleaning_strategy import LastApplyDateCleaningStrategy
# department
from strategies.department_cleaning_strategy import DepartmentCleaningStrategy
# experience
from strategies.experience_cleaning_strategy import ExperienceCleaningStrategy
# posted data
from strategies.posted_date_cleaning_strategy import PostedDateCleaningStrategy

In [13]:
data["Company"].sample(10)

3501                                              NaN
14520                  Posted by Vilwaa Tech Enablers
4151                                        Accenture
22502    Prayatna-centre For Child Development-cochin
27229                                       Hawkscode
3387                                Dslr Technologies
12723                       Tata Consultancy Services
5116                                        Capgemini
12751                                          Google
8855                                  Niveus Solution
Name: Company, dtype: object

In [81]:
ccs = CompanyCleaningStrategy()
df["Company"] = ccs.clean_feature(data["Company"])

df.sample(10)

                          title                    Company
6181   [Database Administrator]  Viable Search Consultants
5207           [Data Scientist]                  Capgemini
19717             [UX Designer]                      Wipro
26140        [Technical Writer]                      Wipro
28075         [DevOps Engineer]               Cardekho.com
27917      [Research Associate]                     Arthan
12657  [Generative AI Engineer]                 Einfochips
20257      [Research Associate]       Aragen Life Sciences
5563             [Data Analyst]                   Altraize
17214            [Data Analyst]                      Wipro

In [15]:
data["Salary"].sample(10)

17882      6-7 Lacs P.A.
5997       Not Disclosed
18886    15-30 Lacs P.A.
17070      Not Disclosed
10065      Not Disclosed
9462       Not Disclosed
24288      Not Disclosed
19905      Not Disclosed
11275      Not Disclosed
1781       Not Disclosed
Name: Salary, dtype: object

In [83]:
scs = SalaryCleaningStrategy()
# df["Salary"] = scs.clean_feature(data["Salary"])
result = scs.clean_feature(data["Salary"])
result.sample(10)
# df = pd.concat([df,result],axis=1)
# df[["Min_Salary",	"Max_Salary",	"Avg_Salary"]]  = result[["Min_Salary",	"Max_Salary",	"Avg_Salary"]]
# df.sample(10)

       Min_Salary  Max_Salary  Avg_Salary
653           NaN         NaN         NaN
1892          NaN         NaN         NaN
20344         NaN         NaN         NaN
22601        10.0        20.0       15.00
2425          NaN         NaN         NaN
14013         2.5         6.0        4.25
11023         5.5        15.5       10.50
10619         1.5         3.0        2.25
816           NaN         NaN         NaN
9977          NaN         NaN         NaN

In [84]:
data["Education"].sample(5)

12853    EducationUG:B.Tech/B.E. in Any SpecializationP...
13891          EducationUG:Any GraduatePG:Any Postgraduate
5992     EducationUG:B.Tech/B.E. in Computer Science En...
11116    EducationUG:B.Tech/B.E. in Production/Industri...
12576    EducationUG:B.Tech/B.E. in Any Specialization,...
Name: Education, dtype: object

In [85]:
ecs = EducationCleaningStrategy()

result = ecs.clean_feature(data["Education"])

result.sample(10)


df["ug_degree"] = result["UG_Degree"]
df["UG_Specialization	"] = result["UG_Specialization"]
df["Pg_degree"] = result["PG_Degree"]
df["PG_Specialization	"] = result["PG_Specialization"]
# df = pd.concat([df, result],axis=1)

df.sample(10)

,title,Company,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t
17339,[Data Engineer],Accenture,Not Required,None,Not Required,None
3695,[Ruby on Rails Developer],Tesark Technologies .,B.Tech,Computers,M.Tech,Computers
26160,[Technical Writer],1 Source Bpo,Not Required,None,None,None
28160,[Project Manager],Vertex Interiors,Not Required,None,Not Required,None
21879,[Web Developer],Softechure It Services,Not Required,None,Not Required,None
13676,[Project Manager],Hindustan Tapes,B.Tech,Mechanical,None,None
23951,[Python Developer],Cyient,Not Required,None,None,None
19049,[Python Developer],Infosys,Not Required,None,Not Required,None
15237,[Data Analyst],CGI,Not Required,None,Not Required,None
20451,[Product Manager],Hexnode,Not Required,None,Not Required,None

In [19]:
data["Description"].sample(10)

8749     This Position reports to: Project Operations M...
8804     Develop new features and user interfaces from ...
7020     We re seeking a passionate and innovative AI/M...
13283    Job Title: Head Contact Center Analytics Locat...
4865     Vorins Technology  is looking for Front-end de...
23746    Design, develop, test, and maintain scalable a...
22223    Role: GCP Kubernetes Engineer (DevOps) Experie...
19928    Hello Candidates, WE ARE HIRING !! Please find...
27096    Job Summary We are seeking an experienced Manh...
28748    We are seeking a highly skilled Data & Machine...
Name: Description, dtype: object

In [20]:
dcs = DescriptionCleaningStrategy()

df["Description"] = dcs.clean_feature(data["Description"])

df["Description"].sample(10)

26455    Money As per DBT rules and eligibility. Qualif...
11905    Role & responsibilities :- DataBase Administra...
10759    Main Roles & Responsibilities Research - 1 Con...
21703    As a Business Analyst, be an SME for Tax and C...
17463    Role Purpose The purpose of this role is to wo...
23334    Diverse Lynx is looking for UX Designer to joi...
18609    Mandatory AWS Cloud Networking: VPC, Peering, ...
17504    we're looking for an experienced Product Manag...
26589    Project Role : Custom Software Engineer Projec...
24424    Project Role : Web Developer Project Role Desc...
Name: Description, dtype: object

In [21]:
data["Role"].sample(10)

11491            Front End Developer ,
8966          Database Administrator ,
9901                 DevOps Engineer ,
7533     Cloud System Administration ,
14429      Full Stack Data Scientist ,
26804                          Other ,
13428                  Data Engineer ,
25390             Back End Developer ,
3450                           Other ,
15466                   Data Analyst ,
Name: Role, dtype: object

In [22]:
rcs = RoleCleaningStrategy()

df["Role"] = rcs.clean_feature(data["Role"])

In [23]:
df["Role"].sample(10)

12794       [Front End Developer]
29878    [Database Administrator]
18989                     [Other]
27575      [Full Stack Developer]
13879          [Business Analyst]
1921           [Network Engineer]
650        [Full Stack Developer]
17682           [DevOps Engineer]
22158           [DevOps Engineer]
8139       [Full Stack Developer]
Name: Role, dtype: object

In [24]:
rccs = RoleCategoryCleaningStrategy()

df["Role_Category"] = rccs.clean_feature(data["Role Category"])

In [25]:
df["Role_Category"].sample(10)

22340                             Treasury
7866                  Software Development
10853                 Software Development
13682                              Ui / Ux
22635                      Technology / It
10299                           It Network
19594    It & Information Security - Other
17089      Data Science & Machine Learning
8056                  Software Development
8019                       Technology / It
Name: Role_Category, dtype: object

In [26]:
data["Industry Type"].sample(10)

12192          IT Services & Consulting ,
13125          IT Services & Consulting ,
25730          IT Services & Consulting ,
22560                  Software Product ,
15703                        TV / Radio ,
11556          IT Services & Consulting ,
20907          IT Services & Consulting ,
3768           IT Services & Consulting ,
13914        Engineering & Construction ,
28983    Pharmaceutical & Life Sciences ,
Name: Industry Type, dtype: object

In [27]:
itc = IndustryTypeCleaningStrategy()

result = itc.clean_feature(data["Industry Type"])

result.sample(10)

,Industry_Types,Primary_Industry,Industry_Count
12948,[IT Services & Consulting],IT Services & Consulting,1
25017,[IT Services & Consulting],IT Services & Consulting,1
15968,[Education & Training],Education & Training,1
16026,[IT Services & Consulting],IT Services & Consulting,1
19506,[IT Services & Consulting],IT Services & Consulting,1
12170,[Banking],Banking,1
19118,[Analytics / Kpo / Research],Analytics / Kpo / Research,1
12061,[Bpm / Bpo],Bpm / Bpo,1
16055,[IT Services & Consulting],IT Services & Consulting,1
4228,[IT Services & Consulting],IT Services & Consulting,1

In [28]:
df["Industry_Type"] = result["Primary_Industry"]
df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,Role,Role_Category,Industry_Type
21502,[Machine Learning Engineer],Angel And Genie,NaN,NaN,NaN,Not Required,None,Not Required,None,Job Title ML Engineer < LI> Experience 3 5 yea...,[AI Engineer],Quality Assurance And Testing,IT Services & Consulting
24515,[DevOps Engineer],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,Project Role : DevOps Engineer Project Role De...,[DevOps Engineer],DevOps,IT Services & Consulting
22381,[Mobile App Developer],QuickInsure,4.5,5.5,5.0,B.Tech,Any Specialization,None,None,Job Profile: Design and develop Android mobile...,[Mobile App Developer],Software Development,Insurance
6789,[Ruby on Rails Developer],Mindpool Technologies,NaN,NaN,NaN,Not Required,None,None,None,We are looking for Ruby on Rails Developer rol...,[Back End Developer],Software Development,IT Services & Consulting
17870,[Other],Reno4u Techno,1.2,1.8,1.5,None,None,None,None,Job Responsibilities 1-Generate new leads and ...,[Other],Back Office,Power
1256,[Web Developer],Adyant SoftTech .,NaN,NaN,NaN,Not Required,None,Not Required,None,;/span> Job Description And Responsibilities: ...,[Full Stack Developer],Software Development,IT Services & Consulting
1684,[UX Designer],Zeta .,NaN,NaN,NaN,Not Required,None,Not Required,None,UX Designer II assists in creating user-center...,[UX Designer],Other Design,IT Services & Consulting
9418,[Other],Synchrony,NaN,NaN,NaN,Not Required,None,Not Required,None,"Job Description: Role Title: AVP, Scrum Master...",[Other],Technology / It,Financial Services
20232,"[Research Associate, AI Researcher]",Williams Lea,NaN,NaN,NaN,Not Required,None,None,None,Comprehend the research requirements of client...,[Other],None,Bpm / Bpo
20302,[Data Engineer],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,About The Role Project Role : Data Engineer Pr...,[Data Engineer],Software Development,IT Services & Consulting

In [29]:
data["Department"]

0                 Data Science & Analytics ,
1                 Data Science & Analytics ,
2                 Data Science & Analytics ,
3                 Data Science & Analytics ,
4                 Data Science & Analytics ,
                        ...
29977                                Other ,
29978    Engineering - Hardware & Networks ,
29979    Engineering - Hardware & Networks ,
29980    Engineering - Hardware & Networks ,
29981    Engineering - Hardware & Networks ,
Name: Department, Length: 29982, dtype: object

In [30]:
dcs = DepartmentCleaningStrategy()

result = dcs.clean_feature(data["Department"])

result.sample(10)

,Department_Cleaned,Primary_Department,Department_Count
11904,"[Engineering, Software Development, Quality As...",Engineering,3
23575,"[Engineering, Hardware, Networks]",Engineering,3
8103,"[Engineering, Software Development, Quality As...",Engineering,3
29238,[Product Management],Product Management,1
7747,"[Engineering, Hardware, Networks]",Engineering,3
5441,"[Engineering, Software Development, Quality As...",Engineering,3
26071,"[Engineering, Software Development, Quality As...",Engineering,3
29070,"[Engineering, Software Development, Quality As...",Engineering,3
23989,"[Engineering, Software Development, Quality As...",Engineering,3
28179,"[Project, Program Management]",Project,2

In [31]:
df["Department"] = result["Primary_Department"]
df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,Role,Role_Category,Industry_Type,Department
891,[Other],University Of Cambridge,NaN,NaN,NaN,Not Required,None,Not Required,None,Applications are invited for the role of Resea...,[Research Associate],Pharmaceutical & Biotechnology,Education & Training,Research & Development
14455,[Data Scientist],IBM,NaN,NaN,NaN,Not Required,None,Not Required,None,"As an Associate Data Scientist at IBM, you wil...",[Data Scientist],Data Science & Machine Learning,IT Services & Consulting,Data Science
14755,[Software Engineer],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,Project Role : Custom Software Engineer Projec...,[Back End Developer],Software Development,IT Services & Consulting,Engineering
16975,[Scrum Master],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,About The Role Project Role : Scrum Master Pro...,"[Technical Writer, Technical Support Specialist]",Software Development,IT Services & Consulting,Engineering
12671,[Research Associate],Enveda Biosciences,NaN,NaN,NaN,Not Required,None,Not Required,None,Let s build the future of medicine together. J...,[Other],Pharmaceutical & Biotechnology,Biotechnology,Research & Development
15529,[Generative AI Engineer],Cognizant,NaN,NaN,NaN,Not Required,None,None,None,Job Summary Returnship Hiring - Women Professi...,[Machine Learning Engineer],Data Science & Machine Learning,IT Services & Consulting,Data Science
27910,[Other],University Of York,NaN,NaN,NaN,Not Required,None,Not Required,None,Department English and Related Literature Sala...,[Research Associate],Pharmaceutical & Biotechnology,Education & Training,Research & Development
24309,[Research Associate],CRF,NaN,NaN,NaN,Not Required,None,Not Required,None,Money As per DBT rules and eligibility. Qualif...,[Research Associate],Pharmaceutical & Biotechnology,Pharmaceutical & Life Sciences,Research & Development
2659,[Data Engineer],Capgemini,12.0,16.0,14.0,Not Required,None,Not Required,None,Job Title: Data Engineer Location: Bangalore N...,[AI Engineer],DBA / Data Warehousing,IT Services & Consulting,Engineering
26259,[Python Developer],Synctric Technology,3.0,4.0,3.5,Not Required,None,None,None,Synctric is looking for a talented Python Deve...,[Back End Developer],Software Development,IT Services & Consulting,Engineering

In [32]:
data["Star_Skills"].sample(10)

12846                                ['software engineer']
10041                                        ['Ux Design']
20534                                                   []
24396                                                   []
12597                            ['customer satisfaction']
25614                           ['Javascript', 'React.Js']
8718     ['Waterfall', 'JIRA', 'SDLC', 'Project Managem...
6562                                                    []
2695      ['Wordpress', 'PHP', 'Bootstrap', 'Codeigniter']
3624                  ['Java', 'Hibernate', 'Spring Boot']
Name: Star_Skills, dtype: object

In [33]:
data["Normal_Skills"].sample(10)

69       ['algorithms', 'python', 'c', 'data pipelines'...
6862     ['image processing', 'kubernetes', 'mlops', 'a...
25853    ['insurance', 'bc', 'data management', 'softwa...
9018     ['financial analysis', 'risk management', 'sta...
14684    ['snowflake', 'data warehouse', 'python', 'dat...
12828    ['application developer', 'workday', 'ai frame...
27787    ['Business Requirement Analysis', 'Business An...
9037            ['C/C++', 'Shell', 'Ansible', 'Debugging']
21712                                                   []
6401     ['SEO Writing', 'Creative Writing', 'Content E...
Name: Normal_Skills, dtype: object

In [34]:
data.iloc[2702:2703]

,Title,Company,Experience,Salary,Location,Education,Star_Skills,Normal_Skills,Posted_Date,Last_Apply_Date,Role,Industry Type,Department,Employment Type,Role Category,Description,Job_URL,Scraped_At,Job_Type
2702,Web Developer,Accenture,3 - 8 years,Not Disclosed,Hyderabad,EducationUG:B.Tech/B.E. in Any SpecializationP...,['web developer'],"['front end', 'css', 'performance monitoring',...",2 days ago,04 Nov 2025,"Full Stack Developer ,","IT Services & Consulting ,","Engineering - Software & QA ,","Full Time, Permanent",Software Development,About The Role Project Role : Web Developer Pr...,https://www.naukri.com/job-listings-web-develo...,2025-12-12T22:52:06.681962,Web Developer

In [35]:
scs = SkillsCleaningStrategy()

result = scs.clean_feature(feature=data[["Star_Skills","Normal_Skills"]])

result.sample(10)

                                         Combined_Skills  Skill_Count
18619  [Vlan Configuration, Vpn Configuration, Switch...           15
12648  [Backend, GitHub, Front End, Architecture, Cod...           10
28240  [Colour, Identify, Design, Interaction, Implem...            9
25202  [Agentic Ai, Mpc, Artificial Intelligence, Mac...            4
17057  [Continuous Integration, Bus, Web Services, En...           31
16800  [It Support, It Helpdesk, Desktop Support, It ...            5
22026  [Data Migration, Project Management, Workflow,...           10
8180   [Computer Science, Ubuntu, Jquery, Git, Linux,...           10
15011  [Node.js, React, NoSQL, Fullstack Development,...           10
16399  [Devops Engineer, Continuous Integration, Oper...           14

In [36]:
# df = pd.concat([df,result],axis = 1)
df["skills"] = result["Combined_Skills"]
df["skill_count"] = result["Skill_Count"]

df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,Role,Role_Category,Industry_Type,Department,skills,skill_count
11461,[Web Developer],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,About The Role Project Role : Web Developer Pr...,[Back End Developer],Software Development,IT Services & Consulting,Engineering,"[Web Developer, Continuous Integration, Cloud ...",16
22368,[Business Analyst],Adobe,NaN,NaN,NaN,Not Required,None,Not Required,None,Understands the Quote to Cash process and reve...,[Back End Developer],Software Development,IT Services & Consulting,Engineering,"[Sap, Networking, Enterprise Applications, Con...",10
19173,[Data Scientist],IBM,NaN,NaN,NaN,Not Required,None,Not Required,None,Scale an existing RAG code base for a producti...,[Data Scientist],Data Science & Machine Learning,IT Services & Consulting,Data Science,"[Data Scientist, Kubernetes, Python, Ai Soluti...",21
21778,[Research Associate],Azim Premji Foundation,NaN,NaN,NaN,Not Required,None,Not Required,None,"You will work with Government school teachers,...",[Research Associate],Pharmaceutical & Biotechnology,Ngo / Social Services / Industry Associations,Research & Development,"[Selection Process, Head Business Development,...",6
22670,[Python Developer],Optum,NaN,NaN,NaN,Not Required,None,None,None,Technical Skills 6+years hands-on experience i...,[Back End Developer],Software Development,Software Product,Engineering,"[Python, Fast Api, Python Development, React, ...",5
27351,[QA Engineer],Netcore Cloud,NaN,NaN,NaN,Not Required,None,None,None,Job Title: QA Engineer 2+ years of experience ...,[AI Engineer],Quality Assurance And Testing,IT Services & Consulting,Engineering,"[Test Engineering, Qa Engineering, Quality Ass...",3
19659,[Product Manager],Eyes On Cloud,NaN,NaN,NaN,Not Required,None,Not Required,None,We are looking for a highly skilled and experi...,[Product Manager],Product Management - Technology,IT Services & Consulting,Product Management,"[Project Management, Product Management, Manag...",5
6468,[Mobile App Developer],Media3 International,NaN,NaN,NaN,Not Required,None,Not Required,None,Media3 International Pvt Ltd. is looking for M...,[Other],Software Development,IT Services & Consulting,Engineering,"[Gsm, Umts, CSS, Software Development, Ux, Sof...",23
14303,[Scrum Master],Wipro,NaN,NaN,NaN,Not Required,None,Not Required,None,About The Role Role Purpose As a trained Scrum...,[Other],Software Development,IT Services & Consulting,Engineering,"[Scrum, Qbr, Apr, Alm, Scrum Master, Sprint, U...",13
28371,[DevOps Engineer],Cardekho.com,NaN,NaN,NaN,Not Required,None,None,None,Key Responsibilities:- Assist in managing and ...,[DevOps Engineer],DevOps,Software Product,Engineering,"[Linux Administration, Shell Scripting, Ci, Cd...",5

In [37]:
data["Experience"].sample(10)

22858      2 - 5 years
4158       0 - 2 years
19811      1 - 2 years
10960     7 - 10 years
1030       2 - 4 years
8143       3 - 8 years
28131    10 - 14 years
25000      7 - 9 years
4713       3 - 6 years
16254      1 - 4 years
Name: Experience, dtype: object

In [38]:
ecs = ExperienceCleaningStrategy()

result = ecs.clean_feature(data["Experience"])

In [39]:
result.sample(10)

       Min_Experience  Max_Experience
17440             2.0             5.0
1416              3.0             6.0
21374             4.0             9.0
11946             0.0             2.0
20365             7.0            12.0
13483             3.0             8.0
6600              2.0             4.0
17666             4.0             8.0
29836             3.0             8.0
17978             3.0             6.0

In [40]:
data.iloc[388:390]

,Title,Company,Experience,Salary,Location,Education,Star_Skills,Normal_Skills,Posted_Date,Last_Apply_Date,Role,Industry Type,Department,Employment Type,Role Category,Description,Job_URL,Scraped_At,Job_Type
388,Data Engineer,Mercedes Benz,2 - 4 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,"['python', 'sql queries', 'big data technologi...","['continuous integration', 'ci/cd', 'microsoft...",3 days ago,05 Aug 2024,"Data Engineer ,","Automobile (Automobile Dealers) ,","Engineering - Software & QA ,","Full Time, Permanent",Software Development,Roles & Responsibilities Design & Build Scalab...,https://www.naukri.com/job-listings-data-engin...,2025-12-07T11:45:19.977953,Data Engineer
389,Data Engineer / Data Architect - WFO _ Chenna...,Intellect Design Arena,3 - 8 years,Not Disclosed,"Hyderabad,Chennai",EducationUG:Any Graduate,"['Vector Db', 'Gcp Bigquery', 'Python']","['Vertex', 'Bigquery']",2 weeks ago,02 Nov 2025,"Data Engineer ,","IT Services & Consulting ,","Engineering - Software & QA ,","Full Time, Permanent",Software Development,"Strong hands-on experience with SQL, Python , ...",https://www.naukri.com/job-listings-data-engin...,2025-12-07T11:45:23.405779,Data Engineer

In [41]:
# df = pd.concat([df,result],axis = 1)
df["Min_Experience"] = result["Min_Experience"]
df["Max_Experience"] = result["Max_Experience"]
df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,Role,Role_Category,Industry_Type,Department,skills,skill_count,Min_Experience,Max_Experience
3186,[Network Engineer],Sysnet,NaN,NaN,NaN,Not Required,None,Not Required,None,Configuring and troubleshooting knowledge of R...,[Network Engineer],It Network,IT Services & Consulting,Engineering,"[Sonicwall, Networking, Vpn, Solarwinds, Routi...",10,0.0,3.0
3133,[Data Architect],National Institute for Smart Government (NISG),NaN,NaN,NaN,Not Required,None,Not Required,None,1 year (extendable to a period of 3 years) Sal...,[Other],IT Security,IT Services & Consulting,Information Technology,"[Cyber Security, Java, Cloud Security, Rust, I...",8,15.0,22.0
17599,[UX Designer],Zeta .,NaN,NaN,NaN,Not Required,None,Not Required,None,UX Designer II assists in creating user-center...,[UX Designer],Other Design,IT Services & Consulting,UX Design,"[Product Management, User Research, Front End,...",10,3.0,4.0
7149,[Web Developer],XcellHost Cloud Services .,NaN,NaN,NaN,Not Required,None,Not Required,None,"Roles and Responsibility Develop high-quality,...",[Back End Developer],Software Development,IT Services & Consulting,Engineering,"[CSS, Web Application, HTML, Web Development, ...",5,0.0,2.0
14981,[UX Designer],Diverse Lynx,NaN,NaN,NaN,Not Required,None,Not Required,None,Diverse Lynx is looking for UX Designer to joi...,[UX Designer],Ui / Ux,IT Services & Consulting,UX Design,"[Interfaces, Ux, Adobe Creative Suite, Prototy...",20,2.0,6.0
10710,[AI Engineer],Google,NaN,NaN,NaN,Not Required,None,Not Required,None,Build virtual agent solutions on Google's core...,[Other],Data Science & Analytics - Other,IT Services & Consulting,Data Science,"[Chatbot, Emerging Technologies, Python, Data ...",16,1.0,3.0
25627,[Cloud Engineer],Techclyde,NaN,NaN,NaN,Not Required,None,Not Required,None,We are looking for skilled Cloud Engineers to ...,[Other],It Infrastructure Services,IT Services & Consulting,Information Technology,"[Cloud, Java, Interpersonal Skills, Programmin...",5,2.0,6.0
7483,[Full Stack Developer],HCLTech,NaN,NaN,NaN,Not Required,None,None,None,Greetings from HCL Tech we are looking for Ful...,[Full Stack Developer],Software Development,IT Services & Consulting,Engineering,"[Java, Fullstack Development, Python]",3,5.0,10.0
21636,[Other],National Institute for Smart Government (NISG),13.0,23.0,18.0,B.Tech,Any Specialization,MCA,Computers,Education Qualification: • B. Tech /MCA /Engin...,[Other],It & Information Security - Other,Management Consulting,Information Technology,"[Data Analysis, Python, SQL, Business Analysis]",4,6.0,10.0
1467,[Project Manager],Wipro,NaN,NaN,NaN,Not Required,None,Not Required,None,Role The purpose of the role is to manage deli...,[Project Manager],Construction / Manufacturing,IT Services & Consulting,Project,"[Project Management, Resource Planning, Sap, T...",13,8.0,10.0

In [42]:
data["Location"].sample(10)

26322                    Pune,Bengaluru,Mumbai (All Areas)
22083                                                 Pune
29937                                            Bengaluru
19211                                              Chennai
6088                                             Bengaluru
6432                                                Rajkot
16143                                               Jaipur
23820                             Ghaziabad( Indirapuram )
12066    Mumbai,Hyderabad,New Delhi,Pune,Ahmedabad,Beng...
5253                                                 Surat
Name: Location, dtype: object

In [43]:
lcs = LocationCleaningStrategy()

result = lcs.clean_feature(data["Location"])

In [44]:
result.sample(10)

,Location_Cities,Primary_Location,Location_Count,Is_Remote
26884,"[Hyderabad, Chennai, Bengaluru]",Hyderabad,3,False
21405,[Noida],Noida,1,False
16565,[Bengaluru],Bengaluru,1,False
10857,[Jaipur],Jaipur,1,False
16238,[Bengaluru],Bengaluru,1,False
20177,[India],India,1,False
26373,[Bengaluru],Bengaluru,1,False
11101,"[Hyderabad, Pune]",Hyderabad,2,False
953,[Bengaluru( Bellandur],Bengaluru( Bellandur,1,False
22352,[Bengaluru],Bengaluru,1,False

In [45]:
df["location"] = result["Primary_Location"]
df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,Role,Role_Category,Industry_Type,Department,skills,skill_count,Min_Experience,Max_Experience,location
1739,[Cloud Engineer],Tata Consultancy Services,NaN,NaN,NaN,Not Required,None,None,None,Greetings from Tata Consultancy Services (TCS)...,[Other],"Bfsi, Investments & Trading - Other",IT Services & Consulting,Bfsi,"[Google Cloud Platform, Vertex, Terraform, Ai ...",5,10.0,15.0,Hyderabad
28374,[DevOps Engineer],Shyena Solutions,NaN,NaN,NaN,Not Required,None,Not Required,None,"At Shyena, our DevOps Engineers are the backbo...",[DevOps Engineer],DevOps,Biotechnology,Engineering,"[Container, Continuous Integration, Cd, Kubern...",21,1.0,6.0,Bengaluru
21665,[Business Analyst],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,About The Role Project Role : Business Analyst...,[Business Analyst],Business Intelligence & Analytics,IT Services & Consulting,Data Science,"[Business Intelligence, Business Process Model...",17,0.0,2.0,Bengaluru
2622,[Research Associate],Radiant Infosolutions,NaN,NaN,NaN,Not Required,None,Not Required,None,We are looking for a talented and enthusiastic...,[Research Associate],Pharmaceutical & Biotechnology,IT Services & Consulting,Research & Development,"[Pdf, Strap, Junior Research Associate, Research]",4,0.0,2.0,New Delhi
20321,[Web Developer],Accenture,NaN,NaN,NaN,Not Required,None,Not Required,None,About The Role Project Role : Web Developer Pr...,[Front End Developer],Software Development,IT Services & Consulting,Engineering,"[MySQL, CSS, Web Application, Jdbc, SQL, Micro...",25,3.0,8.0,Pune
2550,[Generative AI Engineer],Einfochips,NaN,NaN,NaN,Not Required,None,None,None,Role :Generative AI / Agentic AI Engineer Loca...,[Data Scientist],Data Science & Machine Learning,IT Services & Consulting,Data Science,"[Algorithms, Agentic Ai, Generative Ai, Large ...",5,3.0,8.0,Indore
17616,[UX Designer],Intelliod,NaN,NaN,NaN,Not Required,None,Not Required,None,"UX research, Figma, accessibility standards re...",[AI Engineer],Engineering,Power,Production,"[3D Modeling, Software Development, Mechanical...",20,NaN,NaN,Bengaluru
12382,[Scrum Master],Onit,NaN,NaN,NaN,Not Required,None,Not Required,None,Responsibilities: Leading and monitoring the d...,[Project Manager],Technology / It,IT Services & Consulting,Project,"[Computer Science, Pmp, Coding, Software Confi...",10,3.0,8.0,Pune
588,[Technical Writer],Cisco,NaN,NaN,NaN,Not Required,None,Not Required,None,What You'll do: Creates technical/user content...,[Other],Content Management (Print / Online / Electronic),IT Services & Consulting,Content,"[Search Engine Optimization, Keywords, User Co...",6,2.0,7.0,Bengaluru
13868,[Cybersecurity Analyst],Megsoft Business Solutions,NaN,NaN,NaN,Not Required,None,Not Required,None,The ideal candidate should bring a strong unde...,[Cybersecurity Analyst],IT Security,IT Services & Consulting,Information Technology,"[Training, Remediation, Manager Internal Audit...",10,1.0,6.0,Madurai

In [46]:
data["Scraped_At"].sample(10)

29513    2026-03-01T22:36:44.899352
16641    2026-01-16T19:24:06.925318
22208    2026-02-01T20:20:32.959614
14067    2025-12-28T23:00:24.888301
144      2025-12-07T11:14:47.652819
17207    2026-01-21T21:13:24.497692
7676     2025-12-15T21:31:14.405961
4329     2025-12-13T21:27:23.455904
10708    2025-12-18T21:05:26.711031
3122     2025-12-12T23:43:53.773375
Name: Scraped_At, dtype: object

In [47]:
tcs= TimestampCleaningStrategy()

df["timestamp"] = tcs.clean_feature(data["Scraped_At"])

In [48]:
df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,Role,Role_Category,Industry_Type,Department,skills,skill_count,Min_Experience,Max_Experience,location,timestamp
28958,[Generative AI Engineer],HCLTech,16.0,25.0,20.5,None,None,Not Required,None,"PFB the JD: We are looking for strong, hands-o...",[Machine Learning Engineer],Data Science & Machine Learning,IT Services & Consulting,Data Science,"[Machine Learning, Python, Data Structures And...",3,5.0,10.0,Noida,2026-02-26
21498,[Data Scientist],Datamaze Solutions,NaN,NaN,NaN,Not Required,None,Not Required,None,"Full-time ""},""comp-m9fqn7yf5"":{""html"":"" We are...",[Data Scientist],Data Science & Machine Learning,IT Services & Consulting,Data Science,"[Computer Science, Computer Vision, Data Scien...",10,3.0,5.0,Hyderabad,2026-01-28
4817,[Mobile App Developer],Alten,1.0,6.0,3.5,Not Required,None,Not Required,None,"Skills: Xamarin forms, Xaml, C#, MAUI (Multi p...",[Mobile App Developer],Software Development,IT Services & Consulting,Engineering,"[C#, Xaml, Xamarin, Maui]",4,3.0,5.0,Chennai,2025-12-13
6448,[Mobile App Developer],Apex Invention,NaN,NaN,NaN,Not Required,None,Not Required,None,Apex Invention is looking for Mobile App Devel...,[Other],Software Development,IT Services & Consulting,Engineering,"[Gsm, Umts, CSS, Software Development, Ux, Sof...",23,0.0,2.0,Darjeeling,2025-12-14
24066,[Ruby on Rails Developer],Niyati,NaN,NaN,NaN,Not Required,None,Not Required,None,Candidates with minimum 2 years (mandatory) of...,[Other],Software Development,Software Product,Engineering,"[Software Architecture, Backend, Git, Web Serv...",9,2.0,7.0,Remote,2026-02-09
29199,[Product Manager],dishtv,NaN,NaN,NaN,None,None,Not Required,None,Job Title Product ManagerExperience 5+ years o...,[Product Manager],Marketing,Telecom / Isp,Marketing,"[Product Development, Product Management, Go-T...",9,5.0,6.0,Noida( Sector 144,2026-02-26
19105,[Java Developer],Infosys,NaN,NaN,NaN,Not Required,None,None,None,Job description: Hiring Java Developer's with ...,[Other],Software Development,IT Services & Consulting,Engineering,"[Hibernate, J2Ee, Spring Boot, Java Development]",4,3.0,8.0,Hyderabad,2026-01-24
27630,[Ruby on Rails Developer],Finite HR Consulting,NaN,NaN,NaN,Not Required,None,Not Required,None,Our Client Its Alive is looking for Ruby on Ra...,[Web Developer],Content Management (Print / Online / Electronic),Recruitment & Staffing,Content,"[Technical Product Configuration, C++, Design,...",7,2.0,5.0,Mumbai,2026-02-19
3640,[Java Developer],Infosys,NaN,NaN,NaN,Not Required,None,None,None,Job description: Hiring Java Developer with ex...,[Other],Software Development,IT Services & Consulting,Engineering,"[Java, Hibernate, Spring Mvc, J2Ee, Spring Boo...",6,5.0,10.0,Kolkata,2025-12-13
10698,[Business Analyst],PwC India,NaN,NaN,NaN,Not Required,None,Not Required,None,Job Title: Agentic Automation Business Analyst...,[Other],Data Science & Analytics - Other,IT Services & Consulting,Data Science,"[Automation, Artificial Intelligence, Business...",3,5.0,10.0,Noida,2025-12-18

In [49]:
data["Last_Apply_Date"].sample(10)

2461     10 Dec 2025
5151             NaN
18409    26 Jan 2025
23743            NaN
21555    19 Aug 2025
741      22 Aug 2025
23113    20 Nov 2024
4264     06 Dec 2025
3236             NaN
28133    07 Sep 2025
Name: Last_Apply_Date, dtype: object

In [50]:
lcs = LastApplyDateCleaningStrategy()
result = lcs.clean_feature(data["Last_Apply_Date"])
df["last_apply_date"] = result

In [51]:
result.sample(10)

27066          None
13540    2024-02-18
22626    2025-11-16
4344     2025-01-13
21290          None
6989     2025-07-18
20011    2025-08-19
13842    2024-02-01
20372    2025-10-23
18013    2025-06-05
Name: Last_Apply_Date, dtype: object

In [52]:
df.sample(10)

,title,Company,Min_Salary,Max_Salary,Avg_Salary,ug_degree,UG_Specialization\t,Pg_degree,PG_Specialization\t,Description,...,Role_Category,Industry_Type,Department,skills,skill_count,Min_Experience,Max_Experience,location,timestamp,last_apply_date
15962,[Cloud Engineer],Visualpath It Services,4.0,8.0,6.00,Not Required,None,None,None,We’re hiring a Cloud Engineer (3–7 yrs) with s...,...,It Infrastructure Services,Education & Training,Information Technology,"[Cloud Operations, Aws Cloud, Aws Certified, C...",8,3.0,7.0,Hyderabad,2026-01-16,None
25098,[Data Analyst],WPP,NaN,NaN,NaN,Not Required,None,Not Required,None,What youll be doing: Data Strategy & Governanc...,...,Business Intelligence & Analytics,Advertising & Marketing,Data Science,"[Erp, Data Analysis, Data Analytics, Supply Ch...",20,3.0,5.0,Mumbai,2026-02-16,2025-10-07
20149,[Data Analyst],EY,NaN,NaN,NaN,Not Required,None,None,None,Job Title: Data Analyst Experience: 4 - 9 Year...,...,It & Information Security - Other,Management Consulting,Information Technology,"[Data Analysis, Spark, Python, Pyspark]",4,4.0,9.0,Pune,2026-01-27,2025-03-19
29901,[Database Administrator],Mostedge,NaN,NaN,NaN,Not Required,None,Not Required,None,Job Summary: We are seeking an experienced and...,...,DBA / Data Warehousing,IT Services & Consulting,Engineering,"[Mssql Server, Mongodb Atlas, Powershell, Azur...",23,5.0,9.0,Ahmedabad,2026-03-01,None
28082,[DevOps Engineer],Persistent,NaN,NaN,NaN,Not Required,None,None,None,About Persistent We are a trusted Digital Engi...,...,DevOps,IT Services & Consulting,Engineering,"[Continuous Integration, Container, Kubernetes...",31,4.0,8.0,Pune,2026-02-23,2025-01-22
22718,[Ruby on Rails Developer],Tech Stalwart Solution,NaN,NaN,NaN,Not Required,None,Not Required,None,Tech Stalwart Solution Private Limited is look...,...,Software Development,IT Services & Consulting,Engineering,"[C++, CSS, Ajax, Jquery, Rspec, React, Java, G...",30,2.0,7.0,Kolkata,2026-02-01,2025-06-10
11775,[Full Stack Developer],Acenet,NaN,NaN,NaN,Not Required,None,Not Required,None,About Us: AceNet Consulting is a fast-growing ...,...,Software Development,Management Consulting,Engineering,"[Automation, Database Design, Enterprise Appli...",10,4.0,6.0,Pune,2025-12-19,None
10298,[Machine Learning Engineer],NTT DATA,NaN,NaN,NaN,Not Required,None,None,None,Make an impact with NTT DATA Join a company th...,...,It Network,IT Services & Consulting,Engineering,"[Eigrp, Asr, Network Engineering, Nexus, Isr, ...",29,2.0,4.0,Bengaluru,2025-12-17,2025-12-14
7372,[Project Manager],Sengar Consultancy,2.0,5.5,3.75,Not Required,None,None,None,Junior Project Manager Company : Sengar Consul...,...,Technology / It,IT Services & Consulting,Project,"[Coordination, Communication Skills, Time-Mana...",5,0.0,2.0,Noida,2025-12-15,None
26198,[Scrum Master],Barclaycard Payments,NaN,NaN,NaN,Not Required,None,Not Required,None,Join Barclays as a Scrum Master You will be re...,...,Software Development,Financial Services,Engineering,"[Continuous Integration, Cd, Mitigation, Relea...",23,5.0,8.0,Pune,2026-02-16,2025-10-14

In [53]:
df["no_of_applicant"] = None
df["no_of_opening"] = None

In [54]:
df["no_of_applicant"]

0        None
1        None
2        None
3        None
4        None
         ...
29977    None
29978    None
29979    None
29980    None
29981    None
Name: no_of_applicant, Length: 29982, dtype: object

In [55]:
data["Posted_Date"].sample(10)

11484      4 days ago
22272      1 week ago
12177    3+ weeks ago
21552      2 days ago
14885      1 week ago
10549       1 day ago
17307       1 day ago
23775      4 days ago
19846    3+ weeks ago
29453      2 days ago
Name: Posted_Date, dtype: object

In [56]:
pcs = PostedDateCleaningStrategy()

result = pcs.clean_feature(data[["Posted_Date","Scraped_At"]])

In [57]:
result.sample(10)

      Posted_Date_Parsed  Days_Since_Posted
29917         2026-02-08               21.0
15611         2025-12-18               28.0
332           2025-12-06                1.0
19558         2026-01-23                2.0
21765         2026-01-18               14.0
3476          2025-12-09                4.0
23274         2026-02-04                5.0
2959          2025-12-12                0.0
2738          2025-12-12                0.0
21540         2026-01-25                7.0

In [58]:
df["posted_timestamp"] = result["Posted_Date_Parsed"]

In [59]:
df.columns

Index(['title', 'Company', 'Min_Salary', 'Max_Salary', 'Avg_Salary',
       'ug_degree', 'UG_Specialization\t', 'Pg_degree', 'PG_Specialization\t',
       'Description', 'Role', 'Role_Category', 'Industry_Type', 'Department',
       'skills', 'skill_count', 'Min_Experience', 'Max_Experience', 'location',
       'timestamp', 'last_apply_date', 'no_of_applicant', 'no_of_opening',
       'posted_timestamp'],
      dtype='object')

In [60]:
df = df.rename(columns=str.lower)

In [61]:
import os
import sys

In [62]:
os.getcwd()

'd:\\DATA SCIENCE AND ML\\Project\\job_trend_predictor\\src\\cleaners'

In [10]:
import sys
import os

# Go up two levels from notebooks/ → project root
project_root = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Optional: print to confirm
print("Project root added to sys.path:", project_root)
print("Current sys.path[0]:", sys.path[0])

Project root added to sys.path: d:\DATA SCIENCE AND ML\Project\job_trend_predictor
Current sys.path[0]: d:\DATA SCIENCE AND ML\Project\job_trend_predictor

In [11]:
from src.cleaners.job_data_cleaner import JobDataCleaner

In [12]:
config_path = r"D:\DATA SCIENCE AND ML\Project\job_trend_predictor\config\cleaning_config.yaml"

jdc = JobDataCleaner(config_path)

In [14]:
result = jdc.clean(data, "title")

ValueError: Validation failed for column 'title': column is missing or all-null.

In [ ]:
result.columns

Index(['Title', 'Company', 'Experience', 'Salary', 'Location', 'Education',
       'Star_Skills', 'Normal_Skills', 'Posted_Date', 'Last_Apply_Date',
       'Role', 'Industry Type', 'Department', 'Employment Type',
       'Role Category', 'Description', 'Job_URL', 'Scraped_At', 'Job_Type',
       'Title_cleaned'],
      dtype='object')

In [15]:
result = jdc.clean_all(data)

RuntimeError: Pipeline failed on column 'posted_date': Input DataFrame missing required columns: {'Scraped_At', 'Posted_Date'}

In [ ]:
result.columns

Index(['Title', 'Company', 'Experience', 'Salary', 'Location', 'Education',
       'Star_Skills', 'Normal_Skills', 'Posted_Date', 'Last_Apply_Date',
       'Role', 'Industry Type', 'Department', 'Employment Type',
       'Role Category', 'Description', 'Job_URL', 'Scraped_At', 'Job_Type',
       'Title_cleaned', 'Company_cleaned', 'Location_Location_Cities_cleaned',
       'Location_Primary_Location_cleaned', 'Location_Location_Count_cleaned',
       'Location_Is_Remote_cleaned', 'Salary_Min_Salary_cleaned',
       'Salary_Max_Salary_cleaned', 'Salary_Avg_Salary_cleaned',
       'Experience_Min_Experience_cleaned',
       'Experience_Max_Experience_cleaned', 'Education_UG_Degree_cleaned',
       'Education_UG_Specialization_cleaned', 'Education_PG_Degree_cleaned',
       'Education_PG_Specialization_cleaned', 'Skills_Combined_Skills_cleaned',
       'Skills_Skill_Count_cleaned', 'Department_Department_Cleaned_cleaned',
       'Department_Primary_Department_cleaned',
       'Department_Department_Count_cleaned', 'Scraped_At_cleaned',
       'Description_cleaned', 'Last_Apply_Date_cleaned',
       'Posted_Date_Posted_Date_Parsed_cleaned',
       'Posted_Date_Days_Since_Posted_cleaned'],
      dtype='object')

In [ ]:
result["Title_cleaned"].sample(10)

14649       [Research Associate]
691             [Java Developer]
1640            [Cloud Engineer]
4693              [Data Analyst]
17277                    [Other]
24923    [IT Support Specialist]
16579     [Full Stack Developer]
5404             [Data Engineer]
18695    [IT Support Specialist]
11887                    [Other]
Name: Title_cleaned, dtype: object

In [ ]:
result["Company_cleaned"].sample(10)

5925                    Surveysparrow
10143                          Amdocs
27781                           FedEx
22015                         Virtusa
5333                        Accenture
2589                 Chaperon Biotech
3936          Millennium Organisation
19962     SWS Smart Working Solutions
24305    Manpowergroup Services India
3898              ZeMoSo Technologies
Name: Company_cleaned, dtype: object

In [ ]:
result["Education_PG_Degree_cleaned"].sample(10)

17970    Not Required
14367            None
20261    Not Required
2846     Not Required
15608    Not Required
20571    Not Required
20902            None
21537    Not Required
27839    Not Required
1068     Not Required
Name: Education_PG_Degree_cleaned, dtype: object

### Fresher Data

In [1]:
import pandas as pd
from sqlalchemy import create_engine

def get_engine(user, password, host, db):
    # The connection string (URL) follows this format:
    # dialect+driver://username:password@host:port/database
    connection_url = f"mysql+mysqlconnector://{user}:{password}@{host}/{db}"
    
    # create_engine returns an Engine object that pandas understands
    engine = create_engine(connection_url)
    return engine

# usage
engine = get_engine("root", "harshit", "localhost", "job_trends")
data = pd.read_sql_table("raw_job_data", engine)

:

In [ ]:
data.head()

,id,job_id,title,company,experience,salary,location,education,star_skills,normal_skills,...,num_applicants,role,industry_type,department,employment_type,role_category,job_type,description,job_url,scraped_at
0,1,4511587,Python Developer - Fresher,TCS,0-1 Yrs,3-5 Lacs P.A.,Bengaluru,B.Tech/B.E.,"[""Python"", ""Django"", ""SQL""]","[""Git"", ""REST API""]",...,120,Software Development,IT Services,Engineering,Full Time,Programming,python-developer,Looking for fresh graduates...,https://example.com/job1,2026-01-26 10:30:00
1,2,070226018943,Data Analyst,Posted by Tele Infotech,0 - 2 years,2.75-5 Lacs P.A.,"Pimpri-Chinchwad,Pune","EducationUG:Diploma in Any Specialization, Any...","[""Data Analytics""]","[""Large Databases"", ""Google Sheets"", ""Google D...",...,100,Data Science & Analytics - Other,"IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,We are looking for a motivated and detail-orie...,https://www.naukri.com/job-listings-data-analy...,2026-02-08 09:19:53
2,3,020825500433,Trainee AI ML,Vertexplus Technologies,No fixed duration,Unpaid,Jaipur,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""python"", ""data analysis"", ""data analytics"", ...",...,100,Data Science & Machine Learning,"IT Services & Consulting ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,Passion for artificial intelligence and machin...,https://www.naukri.com/job-listings-trainee-ai...,2026-03-11 19:45:59
3,4,040226008743,Data Analytic | Fresher | Business Analytics,Posted by Creative Hands HR,0 - 5 years,2.5-6 Lacs P.A.,"Hyderabad,Chennai,Bengaluru",EducationUG:Any GraduatePG:Any Postgraduate,"[""excel"", ""Business Research"", ""Data Analytics...","[""Data Analyst"", ""Market Research""]",...,100,Data Science & Analytics - Other,"BPM / BPO ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,ANY DEGREE IS PREFERRED 1>good Logical Skills....,https://www.naukri.com/job-listings-data-analy...,2026-02-08 09:20:01
4,5,060226501811,Data Analyst,ADA Global,0 - 1 years,Not Disclosed,Bengaluru,EducationUG:Any GraduatePG:Any Postgraduate,[],"[""python"", ""data analysis"", ""data analytics"", ...",...,100,Business Intelligence & Analytics,"Management Consulting ,","Data Science & Analytics ,","Full Time, Permanent",NA,Fresher Data Analyst,We are seeking a Data Analyst (Fresher) to joi...,https://www.naukri.com/job-listings-data-analy...,2026-03-11 19:04:46

In [ ]:
data.columns

Index(['id', 'job_id', 'title', 'company', 'experience', 'salary', 'location',
       'education', 'star_skills', 'normal_skills', 'posted_date',
       'last_apply_date', 'num_openings', 'num_applicants', 'role',
       'industry_type', 'department', 'employment_type', 'role_category',
       'job_type', 'description', 'job_url', 'scraped_at'],
      dtype='object')

In [ ]:
data.shape

(2551, 23)

In [69]:
result = jdc.clean(data, "title")

ValueError: Validation failed for column 'title'

In [ ]:
result = jdc.clean_all(data)

RuntimeError: Pipeline failed while cleaning column 'Title': Validation failed for column 'Title'

In [ ]:
result.sample(10)